In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')

# Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.
1. First get the webpage https://www.naukri.com/
2. Enter “Data Analyst” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [2]:
#getting the webpage using webdriver
driver1= webdriver.Chrome('chromedriver.exe')
driver1.get('https://www.naukri.com/')

In [3]:
#getting the element to search the job title using xpath
search_job = driver1.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div[1]/input')
search_job

In [4]:
#sending the keyword to the previously selected element 
search_job.send_keys("Data Analyst")

In [5]:
#getting the element to search the job location using xpath and sending the keyword to it
search_location = driver1.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div[1]/input')
search_location.send_keys("Bangalore")

In [6]:
#selecting the button by element using xpath
search_btn=driver1.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
search_btn.click()

In [7]:
#extracting required details in a particular list
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

for i in driver1.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]'):
    job_title.append(i.text)

for i in driver1.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]/span[1]'):
    job_location.append(i.text)

for i in driver1.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]'):
    company_name.append(i.text)
    
for i in driver1.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]/span'):
    experience_required.append(i.text)

In [8]:
#creating dataframe and storing data in it
df1=pd.DataFrame({'Job Title':job_title[:10],'Job Location':job_location[:10],'Company Name':company_name[:10],'Experience Required':experience_required[:10]})
df1

,Job Title,Job Location,Company Name,Experience Required
0,Senior Data Analyst,Bangalore/Bengaluru,Cerner Corporation,8-12 Yrs
1,Senior Data Analyst,Bengaluru/Bangalore,Flipkart,4-6 Yrs
2,Data Analyst,Bangalore/Bengaluru,GSK India,3-8 Yrs
3,Hiring For Cloud Data Analyst,"Hyderabad/Secunderabad, Bangalore/Bengaluru, M...",TCS,4-9 Yrs
4,Data Analyst with SQL,"Gurgaon/Gurugram, Bangalore/Bengaluru",Wipro,4-7 Yrs
5,Junior Data Analyst/ Scientist- Fresher Position,"Kolkata, Gurgaon/Gurugram, Bangalore/Bengaluru",Sejal Consulting Hub,0-3 Yrs
6,Opportunity Master Data Management Developer(D...,"Pune, Bangalore/Bengaluru, Mumbai (All Areas)",Nelito Systems Ltd,6-8 Yrs
7,"Analyst, Data Analytics","Bangalore/Bengaluru, Bangalore",Cardinal Health International India Pvt Ltd.,0-0 Yrs
8,People Service & Support Data Management Analyst,Bangalore/Bengaluru,GSK India,2-7 Yrs
9,Hiring Data Analyst For Global Logic-Immediate...,"Noida, Nagpur, Pune, Gurgaon/Gurugram, Bangalo...",GlobalLogic,4-8 Yrs

# Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. First get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the
location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [9]:
#getting the webpage using webdriver
driver2= webdriver.Chrome('chromedriver.exe')
driver2.get('https://www.naukri.com/')

In [10]:
#getting the element to search the job title using xpath
search_job = driver2.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div[1]/input')
search_job

In [11]:
#sending the keyword to the previously selected element 
search_job.send_keys("Data Scientist")

In [12]:
#getting the element to search the job location using xpath and sending the keyword to it
search_location = driver2.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div[1]/input')
search_location.send_keys("Bangalore")

In [13]:
#selecting the button by element using xpath
search_btn=driver2.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
search_btn.click()

In [14]:
#extracting required details in a particular list
job_title=[]
job_location=[]
company_name=[]

for i in driver2.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]'):
    job_title.append(i.text)

for i in driver2.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]/span[1]'):
    job_location.append(i.text)

for i in driver2.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]'):
    company_name.append(i.text)

In [15]:
#creating dataframe and storing data in it
df2=pd.DataFrame({'Job Title':job_title[:10],'Job Location':job_location[:10],'Company Name':company_name[:10]})
df2

,Job Title,Job Location,Company Name
0,Senior Data Scientist /Senior Software Engineer,"Kochi/Cochin, Hyderabad/Secunderabad, Bangalor...",Terawe Technologies Pvt. Ltd.
1,Sr. Associate Consultant Data Scientist,Bangalore/Bengaluru,Eli Lilly and Company
2,Data Scientist: Advanced Analytics,Bengaluru/Bangalore,IBM
3,Data Scientist (Internal Audit),Bangalore/Bengaluru,Shell
4,Senior Data Scientist,Bangalore/Bengaluru,Walmart
5,Senior Data Scientist,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",I5 Systems Private Limited
6,"Senior Data Scientist, Product Analytics",Bangalore/Bengaluru,Atlassian
7,Sr Data Scientist,Bangalore/Bengaluru,Siemens
8,Lead data Scientist,Bangalore/Bengaluru,"Rakuten, Inc."
9,Associate Data Scientist,"Pune, Bangalore/Bengaluru",Wipro

# Q3: In this question you have to scrape data using the filters available on the webpage as shown below:
You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company name, experience required.
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs
The task will be done as shown in the below steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field.
3. Then click the search button.
4. Then apply the location filter and salary filter by checking the respective boxes
5. Then scrape the data for the first 10 jobs results y

In [16]:
#getting the webpage using webdriver
driver3= webdriver.Chrome('chromedriver.exe')
driver3.get('https://www.naukri.com/')

In [17]:
#getting the element to search the job title using xpath
search_job = driver3.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div[1]/input')
search_job

In [18]:
#sending the keyword to the previously selected element 
search_job.send_keys("Data Scientist")

In [19]:
#selecting the button by element using xpath
search_btn=driver3.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
search_btn.click()

In [20]:
#applying filter as per question
job_location= driver3.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[3]/label/i')
job_location.click()

In [21]:
salary= driver3.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[4]/div[2]/div[2]/label/i')
salary.click()

In [22]:
#extracting required details in a particular list
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

for i in driver3.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]'):
    job_title.append(i.text)

for i in driver3.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]/span[1]'):
    job_location.append(i.text)

for i in driver3.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]'):
    company_name.append(i.text)
    
for i in driver3.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]/span'):
    experience_required.append(i.text)

In [23]:
#creating dataframe and storing data in it
df3=pd.DataFrame({'Job Title':job_title[:10],'Job Location':job_location[:10],'Company Name':company_name[:10],'Experience Required':experience_required[:10]})
df3

,Job Title,Job Location,Company Name,Experience Required
0,Data Scientist / Senior DS/ Team Lead,"Mumbai, Gurgaon/Gurugram(Cyber City +1)",NebulARC Technologies Private Limited,0-4 Yrs
1,Job Opportunity || Data Scientist || HCL Techn...,Delhi / NCR,HCL,2-6 Yrs
2,Senior Data Scientist I,Gurgaon/Gurugram,Delhivery,3-7 Yrs
3,Data Scientist | Python | Machine Learning | D...,"Noida, Gurgaon/Gurugram, Delhi / NCR",Schlesinger Group,0-3 Yrs
4,Openings For Jr/mid/Sr level data Scientists,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",Pluto seven business solutions (p) limited,2-6 Yrs
5,Data Scientist,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",Kyndryl,6-11 Yrs
6,Hiring For Data Analyst / Data Scientist,Noida(Sector-59 Noida),Careerera,2-5 Yrs
7,Data Scientist,Gurgaon/Gurugram(Uday Nagar),Core Diagnostics Private Limited,2-7 Yrs
8,Urgent Hiring For Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru",Mount Talent Consulting Private Limited,1-6 Yrs
9,Urgent Hiring For Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru",Mount Talent Consulting Private Limited,1-6 Yrs

# Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes: Brand, Product Description, Price
The attributes which you have to scrape is ticked marked in the below image.
To scrape the data you have to go through following steps:
1. Go to Flipkart webpage by url : https://www.flipkart.com/
2. Enter “sunglasses” in the search field where “search for products, brands andmore” is written and
click the search icon
3. After that you will reach to the page having a lot of sunglasses. From this pageyou can scrap the
required data as usual.
4. After scraping data from the first page, go to the “Next” Button at the bottom ofthe page , then
click on it.
5. Now scrape data from this page as usual
6. Repeat this until you get data for 100 sunglasses.

In [24]:
#getting the webpage using webdriver
driver4= webdriver.Chrome('chromedriver.exe')
driver4.get('https://www.flipkart.com/')

In [25]:
#selecting cancel button by element using xpath to cancel login popup
search_btn=driver4.find_element_by_xpath('/html/body/div[2]/div/div/button')
search_btn.click()

In [26]:
#getting the element to search the product using xpath
search_job = driver4.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
#sending the keyword to the previously selected element 
search_job.send_keys("sunglasses")

In [27]:
#selecting the button by element using xpath
search_btn=driver4.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
search_btn.click()

In [28]:
#extracting required urls in a particular list
import time
urls=[]

start=0
end=3
for i in range(start,end):
    time.sleep(2)
    nb=driver4.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver4.get(nb[1].get_attribute('href'))
        url=driver4.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))
        
    except:
        driver4.get(nb[0].get_attribute('href'))
        url=driver4.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))

In [30]:
#extracting required details in a particular list
ptitle=[]
des=[]
price=[]
discount=[]

for i in urls:
    driver4.get(i)
    for title_tag in driver4.find_elements_by_xpath('//div[@class="_2WkVRV"]'):
        ptitle.append(title_tag.text)
    
    for des_tag in driver4.find_elements_by_xpath('//a[@class="IRpwTa"]'):
        des.append(des_tag.text)
    
    for price_tag in driver4.find_elements_by_xpath('//div[@class="_30jeq3"]'):
        price.append(price_tag.text)
    
    for dis_tag in driver4.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span'):
        discount.append(dis_tag.text)

In [31]:
#creating dataframe and storing data in it
df4=pd.DataFrame({'Product Title':ptitle[:100],'Description':des[:100],'Price':price[:100],'Discount':discount[:100]})
df4

,Product Title,Description,Price,Discount
0,PIRASO,UV Protection Aviator Sunglasses (54),₹200,87% off
1,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (F...",₹409,48% off
2,Elligator,UV Protection Round Sunglasses (54),₹248,90% off
3,SRPM,UV Protection Wayfarer Sunglasses (50),₹198,84% off
4,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹609,32% off
...,...,...,...,...
95,NuVew,UV Protection Cat-eye Sunglasses (60),₹358,16% off
96,Mi,Polarized Aviator Sunglasses (Free Size),₹999,74% off
97,elegante,UV Protection Oval Sunglasses (Free Size),₹389,86% off
98,GANSTA,UV Protection Aviator Sunglasses (57),₹269,71% off
99,ROYAL SON,UV Protection Retro Square Sunglasses (88),₹569,75% off

# Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link:
https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace.
When you will open the above link you will reach to the below shown webpage.
As shown in the above page you have to scrape the tick marked attributes.These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100 reviews.

In [37]:
#getting the webpage using webdriver
driver5= webdriver.Chrome('chromedriver.exe')
driver5.get('https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace')

In [38]:
#selecting button by element using xpath to view all the reviews
search_btn=driver5.find_element_by_xpath('//*[@id="container"]/div/div[3]/div[1]/div[2]/div[8]/div/div/div[5]/div/a/div/span')
search_btn.click()

In [39]:
#extracting required urls in a particular list
urls=[]

start=0
end=10
for i in range(start,end):
    time.sleep(2)
    nb=driver5.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver5.get(nb[1].get_attribute('href'))
        url=driver5.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))
        
    except:
        driver5.get(nb[0].get_attribute('href'))
        url=driver5.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))

In [40]:
rating=[]
review_summary=[]
full_review=[]

for i in urls:
    driver5.get(i)
    for rt in driver5.find_elements_by_xpath('//div[@class="col _2wzgFH K0kLPL"]/div[1]/div[1]'):
        try:
            rating.append(rt.text)
        except:
            rating.append("NA")
    
    for rs in driver5.find_elements_by_xpath('//p[@class="_2-N8zT"]'):
        try:
            review_summary.append(rs.text)
        except:
            review_summary.append("NA")
    
    for fr in driver5.find_elements_by_xpath('//div[@class="t-ZTKy"]/div/div'):
        try:
            full_review.append(fr.text)
        except:
            full_review.append("NA")

In [41]:
#creating dataframe and storing data in it
df5=pd.DataFrame({'Rating':rating,'Review Summary':review_summary,'Full Review':full_review})
df5

,Rating,Review Summary,Full Review
0,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
1,5,Simply awesome,Really satisfied with the Product I received.....
2,5,Best in the market!,Great iPhone very snappy experience as apple k...
3,5,Perfect product!,Amazing phone with great cameras and better ba...
4,5,Worth every penny,Previously I was using one plus 3t it was a gr...
...,...,...,...
95,5,Just wow!,The ultimate performance\nCamera is superb\nTh...
96,5,Terrific purchase,I use a Note10+ and have been using both iOS a...
97,5,Awesome,The phone is completely good\nAs far as camera...
98,3,Decent product,Everything u ll like it when u use this iPhone...
99,5,Wonderful,Nice value for money good and best price I pho...

# Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.
You have to scrape 4 attributes of each sneaker:
1. Brand
2. Product Description
3. Price
As shown in the below image, you have to scrape the tick marked attributes.

In [42]:
#getting the webpage using webdriver
driver6= webdriver.Chrome('chromedriver.exe')
driver6.get('https://www.flipkart.com')

In [43]:
#selecting cancel button by element using xpath to cancel login popup
search_btn=driver6.find_element_by_xpath('/html/body/div[2]/div/div/button')
search_btn.click()

In [44]:
#getting the element to search the product using xpath
search_job = driver6.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
#sending the keyword to the previously selected element 
search_job.send_keys("sneakers")

In [45]:
#selecting the button by element using xpath
search_btn=driver6.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
search_btn.click()

In [46]:
#extracting required urls in a particular list

urls=[]

start=0
end=3
for i in range(start,end):
    time.sleep(2)
    nb=driver6.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver6.get(nb[1].get_attribute('href'))
        url=driver6.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))
        
    except:
        driver6.get(nb[0].get_attribute('href'))
        url=driver6.find_element_by_xpath("//a[@class='_1LKTO3']")
        urls.append(url.get_attribute('href'))

In [47]:
#extracting required details in a particular list
ptitle=[]
des=[]
price=[]
discount=[]

for i in urls:
    driver6.get(i)
    for title_tag in driver6.find_elements_by_xpath('//div[@class="_2WkVRV"]'):
        try:
            ptitle.append(title_tag.text)
        except:
            ptitle.append("NA")
    
    for des_tag in driver6.find_elements_by_xpath('//div[@class="_2B099V"]/a[1]'):
        try:
            des.append(des_tag.text)
        except:
            des.append("NA")
    
    for price_tag in driver6.find_elements_by_xpath('//div[@class="_30jeq3"]'):
        try:
            price.append(price_tag.text)
        except:
            price.append("NA")
    
    for dis_tag in driver6.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span'):
        try:
            discount.append(dis_tag.text)
        except:
            discount.append("NA")

In [48]:
#creating dataframe and storing data in it
df6=pd.DataFrame({'Product Title':ptitle[:100],'Description':des[:100],'Price':price[:100],'Discount':discount[:100]})
df6

,Product Title,Description,Price,Discount
0,luxury fashion,Luxury Fashionable casual shoes Sneakers For Men,₹429,66% off
1,BRUTON,Lightweight Pack Of 1 Trendy Sneakers Sneakers...,₹199,66% off
2,URBANBOX,Sneakers Sneakers For Men,₹220,77% off
3,Stefano Rads,Classy Sneakers For Men,₹242,65% off
4,HOTSTYLE,Sneakers For Men,₹296,70% off
...,...,...,...,...
95,D-SNEAKERZ,"Casual , Partywear Sneakers Shoes For Men's An...",₹348,15% off
96,Bantox,Sneakers For Men,₹449,70% off
97,Style Tone,Sneakers For Men,₹499,34% off
98,SPARX,SM-496 Sneakers For Men,₹845,60% off
99,Bond Street By Red Tape,Sneakers For Men,"₹1,259",72% off

# Q7: Go to the link - https://www.myntra.com/shoes Set Price filter to “Rs. 7149 to Rs. 14099 ” , Color filter to “Black”, as shown inthe below image.
And then scrape First 100 shoes data you get. The data should include “Brand” of the shoes , Short Shoe
description, price of the shoe as shown in the below image.

In [49]:
#getting the webpage using webdriver
driver7= webdriver.Chrome('chromedriver.exe')
driver7.get('https://www.myntra.com/shoes')

In [50]:
#selecting checkbox using xpath
check_color = driver7.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div')
check_color.click()

In [51]:
check_price = driver7.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div')
check_price.click()

In [52]:
#extracting required urls in a particular list
urls=[]

start=0
end=4
for i in range(start,end):
    time.sleep(2)
    nb=driver7.find_elements_by_xpath("//li[@class='pagination-next']/a")
    url=driver7.find_element_by_xpath("//li[@class='pagination-active']/a")
    urls.append(url.get_attribute('href'))
    driver7.get(nb[0].get_attribute('href'))

In [53]:
#extracting required details in a particular list
ptitle=[]
des=[]
price=[]

for i in urls:
    driver7.get(i)
    for title_tag in driver7.find_elements_by_xpath('//h3[@class="product-brand"]'):
        try:
            ptitle.append(title_tag.text)
        except:
            ptitle.append("NA")
    
    for des_tag in driver7.find_elements_by_xpath('//h4[@class="product-product"]'):
        try:
            des.append(des_tag.text)
        except:
            des.append("NA")
    
    for price_tag in driver7.find_elements_by_xpath('//div[@class="product-price"]/span[1]'):
        try:
            price.append(price_tag.find_element_by_class_name("product-discountedPrice").text.split()[1])
        except:
            price.append(price_tag.text.split()[1])

In [54]:
#creating dataframe and storing data in it
df7=pd.DataFrame({'Product Title':ptitle[:100],'Description':des[:100],'Price':price[:100]})
df7

   Product Title                       Description  Price
0           Puma                 Men Running Shoes  12999
1           Puma         Men Magnify Nitro Running   7799
2        Saint G         Men Mid-Top Chelsea Boots  10500
3       Skechers    Men GO RUN RIDE 9 RunningShoes   8799
4        Bugatti                 Men Running Shoes   7999
..           ...                               ...    ...
95        Clarks  Men Solid Leather Formal Brogues   7999
96       Saint G         Women Kitten Heeled Boots   7565
97   New Balance       Women Training or Gym Shoes   7999
98       Bugatti                      Men Sneakers   8799
99       Saint G        Women Leather Heeled Boots  10115

[100 rows x 3 columns]

# Q8: Go to webpage https://www.amazon.in/
Enter “Laptop” in the search field and then click the search icon.
Then set CPU Type filter to “Intel Core i7” and “Intel Core i9” as shown in the below image:
After setting the filters scrape first 10 laptops data. You have to scrape 3 attributesfor each laptop:
1. Title
2. Ratings
3. Price
As shown in the below image as the tick marked attributes.

In [77]:
#getting the webpage using webdriver
driver8= webdriver.Chrome('chromedriver.exe')
driver8.get('https://www.amazon.in/')

In [78]:
#getting the element to search the product using xpath
search_job = driver8.find_element_by_xpath('/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
#sending the keyword to the previously selected element 
search_job.send_keys("Laptop")

In [79]:
#selecting the button by element using xpath
search_btn=driver8.find_element_by_xpath('/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search_btn.click()

In [80]:
#selecting the button by element using xpath
search_btn=driver8.find_element_by_xpath('//*[@id="p_n_feature_thirteen_browse-bin/12598163031"]/span/a/div/label/i')
search_btn.click()

In [85]:
#extracting the urls in a list
urls=[]
num=0
for i in driver8.find_elements_by_xpath('//a[@class="a-link-normal s-link-style a-text-normal"]'):
    urls.append(i.get_attribute('href'))
    num=num+1
    if num==10:
        break

when i try to fetch the details for i9 sometime checkbox gets disappear

In [86]:
# extracting the data in a list
ptitle=[]
price=[]
rating=[]

for i in urls:
    driver8.get(i)
    try:
        title_tag = driver8.find_element_by_xpath('//span[@class="a-size-large product-title-word-break"]')
        ptitle.append(title_tag.text)
    except:
        ptitle.append("NA")
    try:
        price_tag = driver8.find_element_by_xpath('//span[@class="a-price a-text-price a-size-medium apexPriceToPay"]/span[1]')
        price.append(price_tag.text)
    except:
        ptitle.append("NA")
    try:
        rating_tag = driver8.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]/span')
        rating.append(rating_tag.text.split()[0])
    except:
        rating.append("NA")

In [88]:
#creating dataframe and storing data in it
df8=pd.DataFrame({'Product Title':ptitle,'Price':price,'Rating':rating})
df8

                                       Product Title Price Rating
0  ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...            5
1  Fujitsu UH-X 11th Gen Intel i7 Core 13.3” (33....          4.4
2  ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...            5
3  Mi Notebook Horizon Edition 14 Intel Core i7-1...          4.2
4  HP Pavilion 13, 11th Gen Intel Core i7, 13.3-i...          4.7
5  Lenovo ThinkBook 13s Intel 11th Gen Core i7 13...          4.3
6  LG Gram 17-inches Ultra-Light Intel Evo 11th G...          4.6
7  ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms...          4.3
8  MSI GF75 Thin Gaming, Intel i7-10750H, 17.3" (...          4.4
9  Acer Nitro 5 AN515-57 Gaming Laptop | Intel Co...          4.4

# Q9: Write a python program to scrape data for first 10 job results for Data Scientist Designation in Noida location. You have to scrape company name, No. of days ago when job was posted, Rating of the company.
This task will be done in following steps:
1. First get the webpage https://www.ambitionbox.com/
2. Click on the Job option as shown in the image
3. After reaching to the next webpage, In place of “Search by Designations, Companies, Skills” enter “Data Scientist” and click on search button.
4. You will reach to the following web page click on location and in place of “Search location” enter “Noida” and select location “Noida”.
5. Then scrape the data for the first 10 jobs results you get on the above shown page.
6. Finally create a dataframe of the scraped data.

In [89]:
#getting the webpage using webdriver
driver9= webdriver.Chrome('chromedriver.exe')
driver9.get('https://www.ambitionbox.com/')

In [90]:
#selecting the button by element using xpath
select_job=driver9.find_element_by_xpath('//*[@id="headerWrapper"]/nav/nav/a[6]')
select_job.click()

In [92]:
#sending key as data scientist 
search_job=driver9.find_element_by_xpath('//*[@id="jobs-typeahead"]/span/input')
search_job.send_keys("Data Scientist")

In [93]:
#selecting the button by element using xpath
get_job=driver9.find_element_by_xpath('//*[@id="jobs"]/div[2]/div[1]/div/div/div/button')
get_job.click()

In [95]:
select_location=driver9.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[1]/p')
select_location.click()

In [98]:
search_location=driver9.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[2]/div/div[2]/input')
search_location.send_keys("Noida")

In [99]:
get_location=driver9.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[2]/div/div[3]/div[1]/div[1]/div/label')
get_location.click()

In [107]:
company=[]
period=[]
rating=[]

for i in driver9.find_elements_by_xpath('//p[@class="company body-medium"]'):
    company.append(i.text)

for i in driver9.find_elements_by_xpath('//div[@class="other-info"]/span[1]'):
    period.append(i.text.split()[0])
    
for i in driver9.find_elements_by_xpath('//div[@class="info"]/div/div/a[1]/span'):
    rating.append(i.text)

In [110]:
#creating dataframe and storing data in it
df9=pd.DataFrame({'Company Name':company,'No. of days ago when job was posted':period,'Rating':rating})
df9

                 Company Name No. of days ago when job was posted Rating
0                         HCL                                  4d    3.8
1  Jubilant Foodworks Limited                                  4d    3.9
2        Ameriprise Financial                                  6d    4.0
3                       Zyoin                                  1d    4.1
4                CHT Sapiense                                 9hr    3.8
5                       Paytm                                 12d    3.7
6                CHT Sapiense                                 15d    3.8
7                    GI Group                                 26d    4.1
8                    GI Group                                 26d    4.1
9                    GI Group                                 26d    4.1

# Q10: Write a python program to scrape the salary data for Data Scientist designation. You have to scrape Company name, Number of salaries, Average salary, Minsalary, Max Salary.
The above task will be, done as shown in the below steps:
1. First get the webpage https://www.ambitionbox.com/
2. Click on the salaries option as shown in the image.
3. After reaching to the following webpage, In place of “Search Job Profile” enters “Data Scientist” and then click on “Data Scientist”.
You have to scrape the data ticked in the above image.
4. Scrape the data for the first 10 companies. Scrape the company name, total salary record, average salary, minimum salary, maximum salary, experience required.
5. Store the data in a dataframe.

In [111]:
#getting the webpage using webdriver
driver10= webdriver.Chrome('chromedriver.exe')
driver10.get('https://www.ambitionbox.com/')

In [114]:
#selecting the button by element using xpath
select_sal=driver10.find_element_by_xpath('//*[@id="headerWrapper"]/nav/nav/a[4]')
select_sal.click()

In [117]:
#sending key as data scientist 
search_sal=driver10.find_element_by_xpath('//*[@id="jobProfileSearchbox"]')
search_sal.send_keys("Data Scientist")

In [118]:
get_sal=driver10.find_element_by_xpath('//*[@id="salaries"]/main/section[1]/div[2]/div[1]/span/div/div/div[1]')
get_sal.click()

In [131]:
company=[]
exp=[]
nsal=[]
minsal=[]
avgsal=[]
maxsal=[]

main_tag = driver10.find_element_by_xpath('//div[@class="results-body"]')

for i in main_tag.find_elements_by_xpath('//div[@class="company-info"]/div[1]/a'):
    company.append(i.text)
for i in main_tag.find_elements_by_xpath('//div[@class="salaries sbold-list-header"]'):
    exp.append(i.text.split()[-3])
for i in main_tag.find_elements_by_xpath('//div[@class="company-info"]/div[1]/span'):
    nsal.append(i.text.split()[2])
for i in main_tag.find_elements_by_xpath('//div[@class="salary-values"]/div[1]'):
    minsal.append(i.text)
for i in main_tag.find_elements_by_xpath('//p[@class="averageCtc"]'):
    avgsal.append(i.text)
for i in main_tag.find_elements_by_xpath('//div[@class="salary-values"]/div[2]'):
    maxsal.append(i.text)

In [132]:
#creating dataframe and storing data in it
df10=pd.DataFrame({'Company Name':company,'No. of Salaries':nsal,'Experience ':exp,'Minimum Salary':minsal,'Average Salary':avgsal,'Maximum Salary':maxsal})
df10

,Company Name,No. of Salaries,Experience,Minimum Salary,Average Salary,Maximum Salary
0,Walmart,10,3,₹ 17.7L,₹ 28.7L,₹ 35.0L
1,Ab Inbev,22,3-4,₹ 15.0L,₹ 19.5L,₹ 25.0L
2,ZS,14,2,₹ 9.8L,₹ 15.8L,₹ 20.0L
3,Fractal Analytics,72,2-4,₹ 9.5L,₹ 15.0L,₹ 22.0L
4,Optum,23,3-4,₹ 11.0L,₹ 15.0L,₹ 21.3L
5,UnitedHealth,49,2-4,₹ 7.2L,₹ 13.5L,₹ 20.5L
6,Tiger Analytics,27,3-4,₹ 8.3L,₹ 13.5L,₹ 18.5L
7,Verizon,14,4,₹ 10.0L,₹ 12.7L,₹ 21.0L
8,Ganit Business Solutions,13,4,₹ 8.5L,₹ 12.4L,₹ 15.0L
9,Ericsson,42,3-4,₹ 5.8L,₹ 11.9L,₹ 21.5L