In [343]:
import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
import time

# 1. Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars

In [2]:
driver1=webdriver.Chrome("chromedriver.exe")
driver1.get('https://www.amazon.in/')
time.sleep(5)

In [3]:
search=input("Enter product name to search on an amazon :")

Enter product name to search on an amazon :guitar

In [4]:
search_product=driver1.find_element_by_id('twotabsearchtextbox')
search_product.send_keys(search)

In [5]:
search_btn=driver1.find_element_by_id('nav-search-submit-button')
search_btn.click()

# 2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [6]:
#extracting required urls in a particular list
urls=[]

start=0
end=3
for i in range(start,end):
    time.sleep(2)
    url=driver1.find_elements_by_xpath("//a[@class='a-link-normal s-no-outline']")
    for i in url:
        urls.append(i.get_attribute('href'))
    try:
        nb=driver1.find_element_by_xpath("//a[@class='s-pagination-item s-pagination-next s-pagination-button s-pagination-separator']")
        nb.click()
    except:
        break

In [7]:
len(urls)

143

In [10]:
#extracting required details in a particular list
brand_name=[]
product_name=[]
price=[]
return_exchange=[]
expected_delivery=[]
availability=[]

for i in urls:
    driver1.get(i)
    try:
        brand=driver1.find_element_by_xpath("//*[@id='productOverview_feature_div']/div/table/tbody/tr[1]/td[2]/span")
        brand_name.append(brand.text)
    except:
        brand_name.append("-")
    try:
        pname=driver1.find_element_by_id("productTitle")
        product_name.append(pname.text)
    except:
        product_name.append("-")
    try:
        try:
            pr=driver1.find_element_by_xpath("//span[@class='a-price a-text-price a-size-medium apexPriceToPay']")
            price.append(pr.text)
        except:
            pr=driver1.find_element_by_xpath("//span[@class='a-price aok-align-center priceToPay']")
            price.append(pr.text.replace('\n','.'))
    except:
        price.append("-")
    try:
        re=driver1.find_element_by_xpath("//*[@id='RETURNS_POLICY']/span/div[2]/a")
        return_exchange.append(re.text)
    except:
        return_exchange.append("-")
    try:
        ed=driver1.find_element_by_xpath('//*[@id="ddmDeliveryMessage"]/b')
        expected_delivery.append(ed.text)
    except:
        expected_delivery.append("-")
    try:
        try:
            radio_button=driver1.find_element_by_xpath("//*[@id='newAccordionRow']/div/div[1]/a/i")
            radio_button.click()
            time.sleep(2)
            ava=driver1.find_element_by_xpath("//*[@id='availability']/span")
            availability.append(ava.text)
        except:
            ava=driver1.find_element_by_xpath("//*[@id='availability']/span")
            availability.append(ava.text)
    except:
        availability.append("-")

In [13]:
#creating dataframe and storing data in it
df1=pd.DataFrame({'Brand Name':brand_name,'Product Name':product_name,'Price':price,'Return/Exchange':return_exchange,'Expected Delivery':expected_delivery,'Availability':availability,'Product Url':urls})
df1.sample(10)

,Brand Name,Product Name,Price,Return/Exchange,Expected Delivery,Availability,Product Url
97,MUSTANG,"Mustang Guitar Accessories Kit - Stand, Clip-o...",₹899.00,7 Days Replacement,"Friday, Feb 4",In stock.,https://www.amazon.in/Mustang-Guitar-Accessori...
13,-,AmazonBasics Adjustable Guitar Strap For Elect...,₹529.00,7 Days Replacement,"Wednesday, Feb 2",In stock.,https://www.amazon.in/AmazonBasics-Adjustable-...
93,blueberry,"Blueberry B-D38 38"" Acoustic Guitar Kit Inbuil...","₹2,655.00",7 Days Replacement,"Thursday, Feb 3",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
98,Festra,"Festra 38C, 38 Inch Acoustic Guitar Kit with B...","₹2,560.00",7 Days Replacement,"Thursday, Feb 3",In stock.,https://www.amazon.in/Festra-Acoustic-Guitar-S...
102,Intern,Intern INT-38C-L-NT Left Hand Acoustic Guitar ...,"₹2,771.00",7 Days Replacement,"Wednesday, Feb 2",In stock.,https://www.amazon.in/Intern-INT-38C-L-NT-Acou...
53,JUAREZ,JUAREZ JRZ38CTR/BK 38 Inch Acoustic Guitar wit...,"₹3,179.00",7 Days Replacement,"Wednesday, Feb 2",In stock.,https://www.amazon.in/JUAREZ-JRZ38CTR-BK-Acous...
11,-,AmazonBasics Adjustable Guitar Strap For Elect...,₹449.00,7 Days Replacement,"Wednesday, Feb 2",In stock.,https://www.amazon.in/AmazonBasics-Adjustable-...
57,Kadence,"Kadence Guitar Acoustica Series, Electric Acou...","₹6,499.00",7 Days Replacement,"Friday, Feb 4",In stock.,https://www.amazon.in/Kadence-Acoustica-Ash-Wo...
24,Kadence,Kadence Frontier guitar with Online Guitar lea...,"₹4,999.00",7 Days Replacement,"Friday, Feb 4",In stock.,https://www.amazon.in/Kadence-Frontier-Acousti...
101,YAMAHA,"Yamaha F280 Acoustic Guitar, Tobacco Brown Sun...",-,7 Days Replacement,-,,https://www.amazon.in/Yamaha-Acoustic-Guitar-T...

In [14]:
#extracting data in csv formate
df1.to_csv('amazon_'+search+'_data.csv')

# 3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [2]:
import requests

In [48]:
keywords=['fruits','cars','Machine Learning','Guitar','Cakes']

for keyword in keywords:
    
    driver3=webdriver.Chrome("chromedriver.exe")
    driver3.get('https://images.google.com/?gws_rd=ssl')
    
    search=driver3.find_element_by_xpath('//*[@id="sbtc"]/div/div[2]/input')
    search.send_keys(keyword)

    search_btn=driver3.find_element_by_xpath('//*[@id="sbtc"]/button')
    search_btn.click()
    
    time.sleep(20)
    
    urls=[]

    image_url=driver3.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

    for url in image_url:
        src=url.get_attribute('src')
        if src is not None:
            if (src[0:4] == 'http'):
                urls.append(src)
    
    count=1    
    for img in urls:
        res = requests.get(img)
        file = open(r'C:\Users\Rishi\3D Objects\internship\Web scraping assignment 3 exceptional handling\img\image_'+keyword+'-'+str(count)+'.jpg','wb')
        file.write(res.content)
        file.close()
        if count==10:
            break
        count=count+1
    driver3.close()

# 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV

In [217]:
urls=[]
brand_name=[]
sp_name=[]
colour=[]
ram=[]
rom=[]
pcamera=[]
scamera=[]
display_size=[]
battery_capacity=[]
price=[]

#here i am unable to search oneplus nord instead of it i had put samsung
p_list=['Samsung','pixel 4A']

for plist in p_list:
    
    purls=[]
    
    driver4= webdriver.Chrome('chromedriver.exe')
    driver4.get('https://www.flipkart.com/')

    close_btn=driver4.find_element_by_xpath('/html/body/div[2]/div/div/button')
    close_btn.click()

    search_p = driver4.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input') 
    search_p.send_keys(plist)
    
    search_btn=driver4.find_element_by_xpath('//button[@class="L0Z3Pu"]')
    search_btn.click()
    
    time.sleep(10)
    for url in driver4.find_elements_by_xpath('//a[@class="_1fQZEK"]'):
        purls.append(url.get_attribute('href'))



    for i in purls:
        driver4.get(i)
        read_more=driver4.find_element_by_xpath('//button[@class="_2KpZ6l _1FH0tX"]')
        read_more.click()
        try:
            bname = driver4.find_element_by_xpath('//span[@class="B_NuCI"]')
            brand_name.append(bname.text.split()[0])
        except:
            brand_name.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Model Name':
                    sp=check[1]
                    break
                else:
                    sp='-'
            sp_name.append(sp)
        except:
            sp_name.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Color':
                    col=check[1]
                    break
                else:
                    col='-'
            colour.append(col)
        except:
            colour.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='RAM':
                    ram_=check[1]
                    break
                else:
                    ram_='-'
            ram.append(ram_)
        except:
            ram.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Internal Storage':
                    rom_=check[1]
                    break
                else:
                    rom_='-'
            rom.append(rom_)
        except:
            rom.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Primary Camera':
                    pc=check[1]
                    break
                else:
                    pc='-'
            pcamera.append(pc)
        except:
            pcamera.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Secondary Camera':
                    sc=check[1]
                    break
                else:
                    sc='-'
            scamera.append(sc)
        except:
            scamera.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Display Size':
                    ds=check[1]
                    break
                else:
                    ds='-'
            display_size.append(ds)
        except:
            display_size.append('-')

        try:
            for i in driver4.find_elements_by_xpath('//tr[@class="_1s_Smc row"]'):
                check=i.text.split('\n')
                if check[0]=='Battery Capacity':
                    bc=check[1]
                    break
                else:
                    bc='-'
            battery_capacity.append(bc)
        except:
            battery_capacity.append('-')

        try:
            pr = driver4.find_element_by_xpath('//div[@class="_30jeq3 _16Jk6d"]')
            price.append(pr.text)
        except:
            price.append('-')
        
        urls.append(i)

In [218]:
len(urls)

48

In [219]:
df4=pd.DataFrame({'Brand Name':brand_name,'Smartphone Name':sp_name,'Colour':colour,'RAM':ram,'Internal Storage/ROM':rom,'Primary Camera':pcamera,'Secondary Camera':scamera,'Display size':display_size,'Battery Capacity':battery_capacity,'Price':price,'Product Url':urls})
df4

,Brand Name,Smartphone Name,Colour,RAM,Internal Storage/ROM,Primary Camera,Secondary Camera,Display size,Battery Capacity,Price,Product Url
0,SAMSUNG,Galaxy F12,Sky Blue,4 GB,64 GB,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch),6000 mAh,"₹11,499",<selenium.webdriver.remote.webelement.WebEleme...
1,SAMSUNG,Galaxy F22,Denim Black,4 GB,64 GB,48MP + 8MP + 2MP + 2MP,13MP Front Camera,16.26 cm (6.4 inch),6000 mAh,"₹12,999",<selenium.webdriver.remote.webelement.WebEleme...
2,SAMSUNG,Galaxy M12,Black,4 GB,64 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹11,085",<selenium.webdriver.remote.webelement.WebEleme...
3,SAMSUNG,Galaxy F22,Denim Blue,4 GB,64 GB,48MP + 8MP + 2MP + 2MP,13MP Front Camera,16.26 cm (6.4 inch),6000 mAh,"₹12,999",<selenium.webdriver.remote.webelement.WebEleme...
4,SAMSUNG,Galaxy F12,Sky Blue,4 GB,128 GB,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch),6000 mAh,"₹12,499",<selenium.webdriver.remote.webelement.WebEleme...
5,SAMSUNG,Galaxy F42 5G,Matte Black,6 GB,128 GB,64MP + 5MP + 2MP,8MP Front Camera,16.76 cm (6.6 inch),5000 mAh,"₹20,999",<selenium.webdriver.remote.webelement.WebEleme...
6,SAMSUNG,Galaxy F22,Denim Blue,6 GB,128 GB,48MP + 8MP + 2MP + 2MP,13MP Front Camera,16.26 cm (6.4 inch),6000 mAh,"₹14,999",<selenium.webdriver.remote.webelement.WebEleme...
7,SAMSUNG,Galaxy M32,Light Blue,6 GB,128 GB,64MP + 8MP + 2MP + 2MP,20MP Front Camera,16.26 cm (6.4 inch),6000 mAh,"₹17,180",<selenium.webdriver.remote.webelement.WebEleme...
8,SAMSUNG,Galaxy M12,White,4 GB,64 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹11,099",<selenium.webdriver.remote.webelement.WebEleme...
9,SAMSUNG,Galaxy M12,Blue,4 GB,64 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹11,285",<selenium.webdriver.remote.webelement.WebEleme...
10,SAMSUNG,Guru Music 2,Gold,-,NA,-,-,5.08 cm (2 inch),800 mAh,"₹2,150",<selenium.webdriver.remote.webelement.WebEleme...
11,SAMSUNG,Galaxy F12,Celestial Black,4 GB,64 GB,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch),6000 mAh,"₹11,499",<selenium.webdriver.remote.webelement.WebEleme...
12,SAMSUNG,Galaxy F22,Denim Black,6 GB,128 GB,48MP + 8MP + 2MP + 2MP,13MP Front Camera,16.26 cm (6.4 inch),6000 mAh,"₹14,999",<selenium.webdriver.remote.webelement.WebEleme...
13,SAMSUNG,Galaxy M12,Black,6 GB,128 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹13,506",<selenium.webdriver.remote.webelement.WebEleme...
14,SAMSUNG,Galaxy A52,Awesome Blue,8 GB,128 GB,64MP + 12MP + 5MP + 5MP,32MP Front Camera,16.51 cm (6.5 inch),4500 mAh,"₹25,909",<selenium.webdriver.remote.webelement.WebEleme...
15,SAMSUNG,Galaxy F12,Sea Green,4 GB,64 GB,48MP + 5MP + 2MP + 2MP,8MP Front Camera,16.55 cm (6.515 inch),6000 mAh,"₹11,499",<selenium.webdriver.remote.webelement.WebEleme...
16,SAMSUNG,Galaxy M32 5G,Slate Black,8 GB,128 GB,48MP + 8MP + 5MP + 2MP,13MP Front Camera,16.51 cm (6.5 inch),5000 mAh,"₹21,400",<selenium.webdriver.remote.webelement.WebEleme...
17,SAMSUNG,Galaxy M12,Blue,6 GB,128 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹13,518",<selenium.webdriver.remote.webelement.WebEleme...
18,SAMSUNG,Galaxy F42 5G,Matte Black,8 GB,128 GB,64MP + 5MP + 2MP,8MP Front Camera,16.76 cm (6.6 inch),5000 mAh,"₹22,999",<selenium.webdriver.remote.webelement.WebEleme...
19,SAMSUNG,GURU 1200,Black,-,NA MB,-,-,3.86 cm (1.52 inch),800 mAh,"₹1,575",<selenium.webdriver.remote.webelement.WebEleme...
20,SAMSUNG,Galaxy F42 5G,Matte Aqua,8 GB,128 GB,64MP + 5MP + 2MP,8MP Front Camera,16.76 cm (6.6 inch),5000 mAh,"₹22,999",<selenium.webdriver.remote.webelement.WebEleme...
21,SAMSUNG,Galaxy A52,Awesome Black,6 GB,128 GB,64MP + 12MP + 5MP + 5MP,32MP Front Camera,16.51 cm (6.5 inch),4500 mAh,"₹24,109",<selenium.webdriver.remote.webelement.WebEleme...
22,SAMSUNG,Galaxy M12,White,6 GB,128 GB,48MP Rear Camera,-,16.51 cm (6.5 inch),6000 mAh,"₹13,604",<selenium.webdriver.remote.webelement.WebEleme...
23,SAMSUNG,GURU MUSIC 2,Black,8 MB,0 GB,0MP,0MP Front Camera,5.08 cm (2 inch),800 mAh,"₹2,070",<selenium.webdriver.remote.webelement.WebEleme...
24,Google,Pixel 4a,Just Black,6 GB,128 GB,12.2MP Rear Camera,8MP Front Camera,14.76 cm (5.81 inch),3140 mAh,"₹31,999",<selenium.webdriver.remote.webelement.WebEleme...
25,SAMSUNG,Galaxy M52 5G,Blazing Black,6 GB,128 GB,64MP + 12MP + 5MP,32MP Front Camera,17.02 cm (6.7 inch),5000 mAh,"₹26,350",<selenium.webdriver.remote.webelement.WebEleme...
26,Redmi,Redmi 9A,SeaBlue,2 GB,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch),5000 mAh,"₹7,687",<selenium.webdriver.remote.webelement.WebEleme...
27,Redmi,Redmi 9A,Nature Green,2 GB,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch),5000 mAh,"₹7,699",<selenium.webdriver.remote.webelement.WebEleme...
28,Redmi,Redmi 9A Sport,Metallic Blue,2 GB,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch),5000 mAh,"₹7,785",<selenium.webdriver.remote.webelement.WebEleme...
29,Redmi,Redmi 9A Sport,Coral Green,3 GB,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch),5000 mAh,"₹8,429",<selenium.webdriver.remote.webelement.WebEleme...
30,Redmi,Redmi 9A Sport,Metallic Blue,3 GB,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch),5000 mAh,"₹8,599",<selenium.webdriver.remote.webelement.WebEleme...
31,Redmi,Redmi 9A,Midnight Black,2 GB,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch),5000 mAh,"₹7,725",<selenium.webdriver.remote.webelement.WebEleme...
32,Redmi,Redmi 9A Sport,Carbon Black,2 GB,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch),5000 mAh,"₹7,739",<selenium.webdriver.remote.webelement.WebEleme...
33,ringme,P4O Pro 4G Volte,Green,2 GB,32 GB,8MP Rear Camera,-,16.51 cm (6.5 inch),3000 mAh,"₹5,299",<selenium.webdriver.remote.webelement.WebEleme...
34,Itel,A25,Gradation Purple,1 GB,16 GB,5MP Rear Camera,2MP Front Camera,12.7 cm (5 inch),3020 mAh,"₹4,845",<selenium.webdriver.remote.webelement.WebEleme...
35,Itel,A25,Gradation Green,1 GB,16 GB,5MP Rear Camera,2MP Front Camera,12.7 cm (5 inch),3020 mAh,"₹4,649",<selenium.webdriver.remote.webelement.WebEleme...
36,SAMSUNG,Galaxy A22,Black,6 GB,128 GB,48MP Rear Camera,13MP Front Camera,16.26 cm (6.4 inch),5000 mAh,"₹17,990",<selenium.webdriver.remote.webelement.WebEleme...
37,Redmi,Redmi 9A Sport,Carbon Black,3 GB,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch),5000 mAh,"₹8,435",<selenium.webdriver.remote.webelement.WebEleme...
38,REDMI,10 Prime,Bifrost Blue,4 GB,64 GB,50MP + 8MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),6000 mAh,"₹14,980",<selenium.webdriver.remote.webelement.WebEleme...
39,REDMI,Note 10 Pro,Glacial Blue,8 GB,128 GB,64MP Rear Camera,-,16.94 cm (6.67 inch),5020 mAh,"₹20,235",<selenium.webdriver.remote.webelement.WebEleme...
40,Itel,it5026,Blue,4 MB,4 MB,2MP Rear Camera,-,6.1 cm (2.4 inch),1200 mAh,"₹1,377",<selenium.webdriver.remote.webelement.WebEleme...
41,REDMI,REDMI Note 10 lite,Glacier White,4 GB,64 GB,48MP Rear Camera,-,16.94 cm (6.67 inch),5018 mAh,"₹15,998",<selenium.webdriver.remote.webelement.WebEleme...
42,Itel,A25,Gradation Blue,1 GB,16 GB,5MP Rear Camera,2MP Front Camera,12.7 cm (5 inch),3020 mAh,"₹4,849",<selenium.webdriver.remote.webelement.WebEleme...
43,SAMSUNG,M21 2021 Edition,Arctic blue,4 GB,64 GB,48MP Rear Camera,-,16.26 cm (6.4 inch),6000 mAh,"₹13,265",<selenium.webdriver.remote.webelement.WebEleme...
44,ringme,P4O Pro 4G Volte,STREAM WHITE,2 GB,32 GB,8MP Rear Camera,-,16.51 cm (6.5 inch),3000 mAh,"₹5,299",<selenium.webdriver.remote.webelement.WebEleme...
45,Tecno,Spark 8,Atlantic Blue,3 GB,32 GB,16MP Rear Camera,8MP Front Camera,16.56 cm (6.52 inch),5000 mAh,"₹9,490",<selenium.webdriver.remote.webelement.WebEleme...
46,Tecno,Spark 7T,Magnet Black,4 GB,128 GB,48MP Rear Camera,8MP Front Camera,16.56 cm (6.52 inch),6000 mAh,"₹10,704",<selenium.webdriver.remote.webelement.WebEleme...
47,Tecno,Spark Go 2022,Atlantic Blue,2 GB,32 GB,13MP Rear Camera,-,16.66 cm (6.56 inch),5000 mAh,"₹7,858",<selenium.webdriver.remote.webelement.WebEleme...

In [220]:
#extracting data in csv formate
df4.to_csv('smartphone_data.csv')

# 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [4]:
city=input("Enter the city to find it's geospatial coordinates (latitude, longitude): ")

driver5=webdriver.Chrome("chromedriver.exe")
driver5.get('https://www.google.co.in/maps')

search_city=driver5.find_element_by_id('searchboxinput')
search_city.send_keys(city)

search_btn=driver5.find_element_by_id('searchbox-searchbutton')
search_btn.click()

time.sleep(2)
try:
    coordinates=driver5.current_url.split('@')
    latitude=coordinates[1].split(',')[0]
    longitude=coordinates[1].split(',')[1]

    print('The latitude for the '+city+' city is: '+latitude)
    print('The longitude for the '+city+' city is: '+longitude)
except:
    print('Error occurs while running the code this maybe occurs due to internet connectivity.')

Enter the city to find it's geospatial coordinates (latitude, longitude): Bhadohi
The latitude for the Bhadohi city is: 25.3898937
The longitude for the Bhadohi city is: 82.5333302

# 6. Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) from trak.in.

In [48]:
driver6=webdriver.Chrome("chromedriver.exe")
driver6.get('https://trak.in/')

try:
    btn=driver6.find_element_by_xpath('//*[@id="menu-item-51510"]/a')
    btn.click()
except:
    btn=driver6.find_element_by_xpath('//*[@id="main-navigation"]/li[9]/a')
    btn.click()
    #instead of above code we can also use driver.maximize_window()
    btn1=driver6.find_element_by_xpath('//*[@id="menu-item-51510"]/a')
    btn1.click()

jan='//table[@class="tablepress tablepress-id-54 dataTable no-footer"]/tbody/tr/'
feb='//table[@class="tablepress tablepress-id-55 dataTable no-footer"]/tbody/tr/'
mar='//table[@class="tablepress tablepress-id-56 dataTable no-footer"]/tbody/tr/'
month_list=[jan,feb,mar]

date=[]
startup_name=[]
ind_vertical=[]
sub_vertical=[]
location=[]
i_name=[]
i_type=[]
amt=[]

for month in month_list:
    for d in driver6.find_elements_by_xpath(month+'td[@class="column-2"]'):
        date.append(d.text)
    for sn in driver6.find_elements_by_xpath(month+'td[@class="column-3"]'):
        startup_name.append(sn.text)
    for iv in driver6.find_elements_by_xpath(month+'td[@class="column-4"]'):
        ind_vertical.append(iv.text)
    for sv in driver6.find_elements_by_xpath(month+'td[@class="column-5"]'):
        sub_vertical.append(sv.text)
    for l in driver6.find_elements_by_xpath(month+'td[@class="column-6"]'):
        location.append(l.text)
    for i_n in driver6.find_elements_by_xpath(month+'td[@class="column-7"]'):
        i_name.append(i_n.text)
    for it in driver6.find_elements_by_xpath(month+'td[@class="column-8"]'):
        i_type.append(it.text)
    for a in driver6.find_elements_by_xpath(month+'td[@class="column-9"]'):
        amt.append(a.text)

In [50]:
df6=pd.DataFrame({'Date':date,'Startup Name':startup_name,'Industry / Vertical':ind_vertical,'Sub-Vertical':sub_vertical,'City / Location':location,'Investors Name':i_name,'Investors Type':i_type,'Amount (In USD)':amt})
df6.head()

,Date,Startup Name,Industry / Vertical,Sub-Vertical,City / Location,Investors Name,Investors Type,Amount (In USD)
0,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"
1,28/01/2021,Bombay Shaving Company,Consumer Goods Company,"Shave care, beard care, and skincare products",New Delhi,Reckitt Benckiser,Venture,"6,172,258.50"
2,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
3,19/01/2021,Darwinbox,SaaS,HR Tech,Mumbai,Salesforce Ventures,Seed,"15,000,000"
4,18/01/2021,mfine,Health Tech Startup,AI-powered telemedicine mobile app,Bengaluru,Heritas Capital Management,Venture Round,"16,000,000"

In [51]:
#extracting data in csv formate
df6.to_csv('funding_data.csv')

# 7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [2]:
from selenium.webdriver.common.keys import Keys

driver7=webdriver.Chrome("chromedriver.exe")
driver7.get('https://www.digit.in/')

s_btn=driver7.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[2]/a/img')
s_btn.click()

search=driver7.find_element_by_id('globalPageSearchText')
search.send_keys('gaming laptop')
search.send_keys(Keys.ENTER)

In [3]:
#extracting required urls in a particular list 
#here i am storing the urls for first 3 pages
urls=[]

start=0
end=3
for i in range(start,end):
    time.sleep(2)
    url=driver7.find_elements_by_xpath("//div[@class='searchPage']/a")
    for i in url:
        urls.append(i.get_attribute('href'))
    try:
        try:
            nb=driver7.find_element_by_xpath("/html/body/div[7]/div[2]/div[2]/div[13]/nav/ul/li[7]/a")
            nb.click()
        except:
            nb=driver7.find_element_by_xpath("/html/body/div[7]/div[2]/div[2]/div[13]/nav/ul/li[6]/a")
            nb.click()
    except:
        break

In [18]:
#extracting required details in a particular list
brand_name=[]
model_name=[]
price=[]
ram=[]
storage=[]
processor=[]
cpu_speed=[]
graphics=[]
display_size=[]
availablity=[]


for i in urls:
    driver7.get(i)
    try:
        brand=driver7.find_element_by_xpath("/html/body/div[4]/div[2]/div[1]/nav/ol/li[3]/a")
        brand_name.append(brand.text)
    except:
        brand_name.append("-")
    try:
        for chk in driver7.find_elements_by_xpath('//*[@id="specs-basic-information"]/div[2]/table/tbody/tr'):
            check=chk.text.split(' : ')
            if check[0]=='Model Name':
                model=check[1]
                break
            else:
                model='-'
        model_name.append(model)
    except:
        model_name.append("-")
    try:
        pr=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[4]/div/h2/strong')
        price.append(pr.text)
    except:
        price.append("-")
    try:        
        ram_=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[4]/div/p[2]/strong')
        ram.append(ram_.text.split('/')[1])
    except:
        ram.append("-")
    try:
        st=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[4]/div/p[2]/strong')
        storage.append(st.text.split('/')[0])
    except: 
        storage.append("-")
    try:
        pro=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[3]/div/p[2]/strong')
        processor.append(pro.text.split('|')[0])
    except:
        processor.append("-")
    try:
        cpu=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[3]/div/p[2]/strong')
        cpu_speed.append(cpu.text.split('|')[1])
    except:
        cpu_speed.append("-")
    try:
        for chk in driver7.find_elements_by_xpath('//*[@id="specs-processor"]/div[2]/table/tbody/tr'):
            check=chk.text.split(' : ')
            if check[0]=='Graphics Processor':
                graphic=check[1]
                break
            else:
                graphic='-'
        graphics.append(graphic)
    except:
        graphics.append("-")
    try:
        ds=driver7.find_element_by_xpath('//*[@id="overview"]/div[3]/div[3]/div/ul/li[2]/div/p[2]/strong')
        display_size.append(ds.text)
    except:
        display_size.append("-")
    try:
        ava=driver7.find_element_by_xpath('//span[@class="status"]')
        availablity.append(ava.text)
    except:
        availablity.append("-")

In [20]:
df7=pd.DataFrame({'Brand Name':brand_name,'Model Name':model_name,'Price':price,'RAM':ram,'Storage':storage,'Processor':processor,'CPU speed':cpu_speed,'Graphics':graphics,'Display size':display_size,'Availablity':availablity,'Product Url':urls})
df7.sample(5)

,Brand Name,Model Name,Price,RAM,Storage,Processor,CPU speed,Graphics,Display size,Availablity,Product Url
17,Lenovo,Ideapad Gaming 3 Core i5 10th Gen,"₹ 79,990",8GB DDR4,512 GB SSD,Core I5,3.0 GHz,NVIDIA Geforce GTX NVIDIA,"15.6"" (1920 X 1080)",AVAILABLE,https://www.digit.in/laptops/lenovo-ideapad-ga...
12,Asus,GA401QH-HZ071TS,"₹ 74,990",4 GBGB GDDR6,512 GB SSD,AMD Ryzen 7 5800HS,3.0 GHz,NVIDIA GeForce GTX 1650,"14"" (1920 X 1080)",AVAILABLE,https://www.digit.in/laptops/asus-rog-zephyrus...
26,Dell,G15 Gaming,"₹ 85,489",16 GBGB DDR4,512 GB SSD,10th Generation Intel® Core™ I5-10200H,NA,NVIDIA® GeForce RTX™ 3050,"15.6"" (1920 X 1080)",-,https://www.digit.in/laptops/dell-g15-gaming-1...
19,HP,14s- DQ2535TU,"₹ 58,990",8 GBGB DDR4,512 GB SSD,Intel Core I5 11th Gen,4.2 GHz,Intel Integrated Iris Xe,"14"" (1366 X 768)",AVAILABLE,https://www.digit.in/laptops/hp-14s-core-i5-11...
9,Asus,TUF Gaming A15,"₹ 96,990",16GBGB DDR4,1 TB HDD,AMD Ryzen 9 4900H,3.3 GHz,Dedicated NVIDIA GeForce GTX 1660 Ti GDDR6,"15.6 Inch"" (1920 X 1080)",AVAILABLE,https://www.digit.in/laptops/asus-tuf-gaming-a...

In [21]:
#extracting data in csv formate
df7.to_csv('gaming_laptop_data.csv')

# 8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [29]:
driver8=webdriver.Chrome("chromedriver.exe")
driver8.get('https://www.forbes.com/')

menu_btn=driver8.find_element_by_xpath('/html/body/div[1]/header/nav/div[1]/button[1]')
menu_btn.click()

bill_btn=driver8.find_element_by_xpath('/html/body/div[1]/header/nav/div[3]/ul/li[1]')
bill_btn.click()

billionaire_btn=driver8.find_element_by_xpath('/html/body/div[1]/header/nav/div[3]/ul/li[1]/div[2]/ul/li[2]/a')
billionaire_btn.click()

In [36]:
rank=[]
name=[]
net_worth=[]
age=[]
citizenship=[]
source=[]
industry=[]

for i in range(0,14):

    for rk in driver8.find_elements_by_xpath('//div[@class="rank"]'):
        rank.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="personName"]'):
        name.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="netWorth"]'):
        net_worth.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="age"]'):
        age.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="countryOfCitizenship"]'):
        citizenship.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="source-column"]'):
        source.append(rk.text.split('.')[0])
        
    for rk in driver8.find_elements_by_xpath('//div[@class="category"]/div'):
        industry.append(rk.text.split('.')[0])       
        
    try:
        next_btn=driver8.find_element_by_xpath('//button[@class="pagination-btn pagination-btn--next "]')
        next_btn.click()
    except:
        break

In [38]:
df8=pd.DataFrame({'Rank':rank,'Name':name,'NET worth':net_worth,'Age':age,'Country / Territory':citizenship,'Source':source,'Industry':industry})
df8

,Rank,Name,NET worth,Age,Country / Territory,Source,Industry
0,1,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
2750,2674,Daniel Yong Zhang,$1 B,49,China,e-commerce,Technology
2751,2674,Zhang Yuqiang,$1 B,65,China,Fiberglass,Manufacturing
2752,2674,Zhao Meiguang,$1 B,58,China,gold mining,Metals & Mining
2753,2674,Zhong Naixiong,$1 B,58,China,conglomerate,Diversified
2754,2674,Zhou Wei family,$1 B,54,China,Software,Technology

In [39]:
#extracting data in csv formate
df8.to_csv('billionaires_data.csv')

# 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [347]:
driver9=webdriver.Chrome("chromedriver.exe")
driver9.get('https://www.youtube.com/watch?v=VCQvgWKRMLU')

driver9.maximize_window()

In [357]:
username=[]
comment=[]
likes=[]
period=[]

scroll=driver9.find_element_by_xpath('//h1[@class="title style-scope ytd-video-primary-info-renderer"]')
driver9.execute_script("arguments[0].scrollIntoView(true);",scroll)

time.sleep(1)

for i in range(0,50):
    for scroll in driver9.find_elements_by_id('body'):
        driver9.execute_script("arguments[0].scrollIntoView(true);",scroll)
        time.sleep(0.5)
        username.append(scroll.text.split('\n')[0])
        
        try:
            com=scroll.find_element_by_id('content')
            comment.append(com.text)
        except:
            comment.append('-')
            
        try:
            like=scroll.find_element_by_id('vote-count-middle')
            likes.append(like.text)
        except:
            likes.append('-')
            
        period.append(scroll.text.split('\n')[1].split('(')[0])

        if len(username)==500:
            break
    if len(username)==500:
        break

In [364]:
df9=pd.DataFrame({'Username':username,'Comment':comment,'Likes':likes,'Time':period})
df9.head(10)

,Username,Comment,Likes,Time
0,Aklesh Bhamore,Watching Ramcharan & NTR Dancing Together Is ...,12K,2 months ago
1,Humorwale,Energy is out of this world.,2.5K,1 month ago
2,Kalpana Shekar,This song showed the true potential of our to...,52,6 days ago
3,Dark,So obsessed with this song and dance (moves),212,3 weeks ago
4,Vaibhav Pratap,"Great to see boundaries between Bollywood, tol...",1.1K,1 month ago
5,Arman Munna,Not only they are fast but also perfectly sync...,32,6 days ago
6,surya Prakash,ఒరెయ్ చారి ఈ హిందీ వెర్షన్ ఏంట్రా తెలుగు వెర్ష...,3.1K,2 months ago
7,Garima,It's just an explosion of energy of joy and en...,197,3 weeks ago
8,gautam ravi,U can feel the energy... it's thumping in the ...,234,1 month ago
9,N,3:05 Goosebumps....️,18,5 days ago

In [365]:
#extracting data in csv formate
df9.to_csv('video_data.csv')

# 10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [235]:
driver10=webdriver.Chrome("chromedriver.exe")
driver10.get('https://www.hostelworld.com/')

driver10.maximize_window()

In [241]:
search=driver10.find_element_by_xpath('//*[@id="search-input-field"]')
search.send_keys('London')

In [242]:
search_list=driver10.find_element_by_xpath('//*[@id="predicted-search-results"]/li[2]')
search_list.click()

search_btn=driver10.find_element_by_id('search-button')
search_btn.click()

In [243]:
#extracting required urls in a particular list 
urls=[]
hostel_name=[]
distance=[]
rating=[]
t_reviews=[]
o_review=[]
p_price=[]
d_price=[]
facilities=[]
description=[]


start=0
end=3
for i in range(start,end):
    time.sleep(2)
    
    for url in driver10.find_elements_by_xpath("//a[@class='view-button']"):
        urls.append(url.get_attribute('href'))
        
    try:
        for hname in driver10.find_elements_by_xpath('//h2[@class="title title-6"]'):
            hostel_name.append(hname.text)
    except:
        hostel_name.append('-')
        
    try:
        for dist in driver10.find_elements_by_xpath('//span[@class="description"]'):
            distance.append(dist.text.split('-')[1].split()[0])
    except:
        distance.append('-')
        
    try:
        for r in driver10.find_elements_by_xpath('//div[@class="rating rating-summary-container big"]'):
            rat=r.text.split('\n')
            if len(rat)==3:
                rating.append(rat[0])
            else:
                rating.append('-')            
    except:
        rating.append('-')
        
    try:
        for tr in driver10.find_elements_by_xpath('//div[@class="reviews"]'):
            t_reviews.append(tr.text)
    except:
        t_reviews.append('-')
        
    try:
        for o_r in driver10.find_elements_by_xpath('//div[@class="rating rating-summary-container big"]/div/div/span'):
            o_review.append(o_r.text)
    except:
        o_review.append('-')
        
    try:
        for p in driver10.find_elements_by_xpath('//div[@class="prices-col"]/a/div[1]'):
            pr=p.text.split('\n')
            if pr[0]=='Privates From':
                p_pr=pr[1].split()
                try:
                    p_price.append(p_pr[1])
                except:
                    p_price.append(p_pr[0])
            else:
                p_price.append('-')
    except:
        p_price.append('-')
        
    try:
        for p in driver10.find_elements_by_xpath('//div[@class="prices-col"]/a/div[2]'):
            pr=p.text.split('\n')
            if pr[0]=='Dorms From':
                p_pr=pr[1].split()
                try:
                    d_price.append(p_pr[1])
                except:
                    d_price.append(p_pr[0])
            else:
                d_price.append('-')
    except:
        d_price.append('-')
        
    try:
        next_btn=driver10.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_btn.click()
    except:
        break
        
        
        
for url in urls:
    driver10.get(url)
    
    try:
        pd_btn=driver10.find_element_by_xpath('//*[@id="__layout"]/div/div[1]/section/div[6]/div/div[2]/div/div/a')
        pd_btn.click()  
        try:
            pd=driver10.find_element_by_xpath('//*[@id="__layout"]/div/div[1]/section/div[6]/div/div[2]/div/div/div[2]')
            description.append(pd.text)       
        except:
            description.append('-')                 
    except:
        try:
            pd=driver10.find_element_by_xpath('//*[@id="__layout"]/div/div[1]/section/div[6]/div/div[2]/div/div/div[2]')
            description.append(pd.text)       
        except:
            description.append('-')               
     
    try:
        fac=''
        for f in driver10.find_elements_by_xpath('//ul[@class="facility-sections"]/li/ul/li'):
            fac=fac+','+f.text
        facilities.append(fac)
    except:
        facilities.append('-')

In [251]:
urls[1]

'https://www.hostelworld.com/pwa/hosteldetails.php/Wombat-s-The-City-Hostel-London/London/88047?from=2022-02-05&to=2022-02-08&guests=2'

In [249]:
df10=pd.DataFrame({'Hostel Name':hostel_name,'Distance from city centre':distance,'Rating':rating,'Total numbers of Reviews':t_reviews,'Overall Review':o_review,'Privates from price':p_price,'Dorms from price':d_price,'Facilities':facilities,'Description':description})
df10.sample(10)

,Hostel Name,Distance from city centre,Rating,Total numbers of Reviews,Overall Review,Privates from price,Dorms from price,Facilities,Description
5,Pickwick Hall,2.3km,9.0,2276 Total Reviews,Superb,Rs5081,-,",Free Breakfast,Linen Included,Free Internet A...",Pickwick Hall provides accommodation for touri...
25,Phoenix Hostel,4.2km,7.8,3481 Total Reviews,Very Good,Rs4694,Rs1609,",Linen Included,Free City Maps,Free WiFi,Free ...",*Please note we are operating on LIMITED recep...
59,Golders Park Hotel,10.4km,-,0 Total Reviews,No Rating,Rs9857,-,",Linen Included,Free Parking,Towels Included,F...","Set in London, 4.3 miles from London Zoo, Gold..."
8,Astor Hyde Park,4.3km,8.4,11386 Total Reviews,Fabulous,-,Rs1965,",Linen Included,Free City Maps,Free WiFi,Free ...",Located in the most beautiful and charming nei...
42,Kip Hotel,6.8km,9.6,52 Total Reviews,Superb,Rs5691,-,",Towels Included,Free WiFi,Key Card Access,Bre...",Kip is on a mission to bring the world style a...
15,Prime Backpackers Angel,3.6km,9.2,531 Total Reviews,Superb,Rs6704,Rs2312,",Linen Included,Free City Maps,Towels Included...",The hostel is housed in a historic building in...
63,TLK Apartments & Hotel,19.9km,-,0 Total Reviews,No Rating,Rs6013,-,",Linen Included,Free Parking,Towels Included,F...",To be in tune with what is expected of a hotel...
28,St Christopher's Oasis-Female Only,1.8km,7.9,620 Total Reviews,Very Good,Rs5280,Rs2021,",Linen Included,Free City Maps,Towels Included...",COVID 19 Policy Update.\nIn response to Corona...
10,No.8 Seven Sisters,9km,6.8,3689 Total Reviews,Good,-,Rs808,",Linen Included,Free WiFi,Security Lockers,Key...","For Great Facilities, Comfort & Affordability ..."
36,Hostel One Notting Hill,5.5km,7.6,1314 Total Reviews,Very Good,Rs8000,Rs1847,",Linen Included,Free WiFi,Free Internet Access...",The perfect place for solo travelers to connec...

In [250]:
#extracting data in csv formate
df10.to_csv('hostel_data.csv')