In [1]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in c:\anaconda\lib\site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\anaconda\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=13c618d94557891c1c841fd2f85be60af795e264914e4b8cd8907d27ce1575db
  Stored in directory: c:\users\rishi\appdata\local\pip\cache\wheels\75\78\21\68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1

In [3]:
!pip install requests

Requirement already satisfied: requests in c:\anaconda\lib\site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\anaconda\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda\lib\site-packages (from requests) (1.26.4)

# 1) Write a python program to display all the header tags from wikipedia.org.

In [23]:
from bs4 import BeautifulSoup
import requests

In [24]:
page=requests.get('https://en.wikipedia.org')

In [15]:
page

In [16]:
soup=BeautifulSoup(page.content)

In [47]:
header=soup.find('h1',class_="firstHeading")

In [48]:
header.text

'Main Page'

In [32]:
header_list=[]

for i in soup.find_all('h1'):
    header_list.append(i.text)
for i in soup.find_all('h2'):
    header_list.append(i.text)
for i in soup.find_all('h3'):
    header_list.append(i.text)
for i in soup.find_all('h4'):
    header_list.append(i.text)
for i in soup.find_all('h5'):
    header_list.append(i.text)
for i in soup.find_all('h6'):
    header_list.append(i.text)

In [34]:
header_list

['Main Page',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages',
 'Navigation menu',
 '\nPersonal tools\n',
 '\nNamespaces\n',
 '\nVariants\nexpanded\ncollapsed\n',
 '\nViews\n',
 '\nMore\nexpanded\ncollapsed\n',
 '\nSearch\n',
 '\nNavigation\n',
 '\nContribute\n',
 '\nTools\n',
 '\nPrint/export\n',
 '\nIn other projects\n',
 '\nLanguages\n']



# 2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [117]:
pg2=requests.get("https://www.imdb.com/chart/top/?ref_=nv_mv_250")

In [118]:
pg2

In [154]:
soup2=BeautifulSoup(pg2.content,'html.parser')

In [155]:
movie_tag=soup2.find('td',  class_='titleColumn')
movie_title=movie_tag.find('a')
print(mt)

<a href="/title/tt0111161/" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">The Shawshank Redemption</a>

In [156]:
movie_title=[]
movie_year=[]
movie_rating=[]
num=0
for i in soup2.find_all('td',  class_='titleColumn'):
    title=i.find('a')
    movie_title.append(title.text)
    year=i.find('span', class_='secondaryInfo')
    movie_year.append(year.text)
    num=num+1
    if num==100:
        break
num=0
for i in soup2.find_all('td', class_='ratingColumn imdbRating'):
    rating=i.find('strong')
    movie_rating.append(rating.text)
    num=num+1
    if num==100:
        break

In [157]:
print(len(movie_title),len(movie_year),len(movie_rating))

100 100 100

In [148]:
import pandas as pd

In [158]:
df=pd.DataFrame({'Movie Title':movie_title,'Rating':movie_rating,'Year of release':movie_year})
df

                              Movie Title Rating Year of release
0                The Shawshank Redemption    9.2          (1994)
1                           The Godfather    9.1          (1972)
2                  The Godfather: Part II    9.0          (1974)
3                         The Dark Knight    9.0          (2008)
4                            12 Angry Men    8.9          (1957)
..                                    ...    ...             ...
95                                 Jagten    8.3          (2012)
96                    Requiem for a Dream    8.3          (2000)
97                    Singin' in the Rain    8.3          (1952)
98                     North by Northwest    8.3          (1959)
99  Eternal Sunshine of the Spotless Mind    8.3          (2004)

[100 rows x 3 columns]



# 3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year ofrelease) and make data frame.

In [159]:
pg3=requests.get("https://www.imdb.com/india/top-rated-indian-movies/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=461131e5-5af0-4e50-bee2-223fad1e00ca&pf_rd_r=JC8DKTDE2R9YQTMZTA54&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=india.toprated&ref_=fea_india_ss_toprated_india_tr_india250_sm")

In [160]:
soup3=BeautifulSoup(pg3.content,'html.parser')

In [161]:
movie_title=[]
movie_year=[]
movie_rating=[]
num=0
for i in soup3.find_all('td',  class_='titleColumn'):
    title=i.find('a')
    movie_title.append(title.text)
    year=i.find('span', class_='secondaryInfo')
    movie_year.append(year.text)
    num=num+1
    if num==100:
        break
num=0
for i in soup3.find_all('td', class_='ratingColumn imdbRating'):
    rating=i.find('strong')
    movie_rating.append(rating.text)
    num=num+1
    if num==100:
        break

In [162]:
print(len(movie_title),len(movie_year),len(movie_rating))

100 100 100

In [163]:
df=pd.DataFrame({'Movie Title':movie_title,'Rating':movie_rating,'Year of release':movie_year})
df

            Movie Title Rating Year of release
0              Jai Bhim    8.5          (2021)
1     Pariyerum Perumal    8.5          (2018)
2               Nayakan    8.5          (1987)
3            Anbe Sivam    8.5          (2003)
4     C/o Kancharapalem    8.5          (2018)
..                  ...    ...             ...
95  Munna Bhai M.B.B.S.    8.1          (2003)
96            Sarfarosh    8.1          (1999)
97                Queen    8.1          (2013)
98                 Roja    8.1          (1992)
99       Dil Chahta Hai    8.1          (2001)

[100 rows x 3 columns]


# 4) Write a python program to scrape product name, price and discounts from https://meesho.com/bagsladies/pl/p7vbp .

In [164]:
pg4=requests.get("https://meesho.com/bags-ladies/pl/p7vbp")

In [165]:
pg4

In [166]:
soup4=BeautifulSoup(pg4.content,'html.parser')

In [182]:
link='Card__BaseCard-sc-b3n78k-0 dUNFgg NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS'
pname_tag=soup4.find('div', class_=link)
pname=pname_tag.find('p')
pprice=pname_tag.find('h5')

In [186]:
print(pname.text,pprice.text)

Women PINK Shoulder Bag - Extra Spacious ₹194

In [180]:
pname=[]
for i in soup4.find_all('div', class_=link):
    name=i.find('p')
    pname.append(name.text)

In [181]:
pname

['Women PINK Shoulder Bag - Extra Spacious',
 'JUTE-TFLY-01cRED-5 handbag',
 'Elegant Fashionable Women Handbags',
 'Gorgeous Attractive Women Handbags',
 'X-DIAMOND ,PINK,STONE, HANDBANG,PACK OF 1',
 'Jute White Color Floral Printed Fancy Bag, Beach Bag, Shopping Bag, spacious Bag, Trendy Women Bag, Casual Bag with Zipper Closer',
 'Latest design combo handbag set',
 'hand bag with golden chain',
 'Women Handbags ',
 'Classic Fashionable Women Handbags',
 'Hand bag',
 'Womens Shoulder Hand Bag(Beige)',
 'Voguish Fancy Women Handbags',
 'Hand bag',
 'Hand bag for women/hand bag/ solid print  bag/stylish handbag/wedding bag/handbag set for women ',
 'Leather Women Stylish Handbag/purse | Shoulder Hanbags for College Office Girls - Blue',
 'Graceful Versatile Women Handbags',
 'Leather Women Stylish Handbag/purse | Shoulder Hanbags for College Office Girls - Brown',
 'Women Handle Held Bag (Black)',
 'D-Cut Cloth Carry Bag']