# 1) Write a python program to display all the header tags from wikipedia.org.

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
page=requests.get('https://en.wikipedia.org')

In [3]:
page

In [4]:
soup=BeautifulSoup(page.content)

In [5]:
header=soup.find('h1',class_="firstHeading")

In [6]:
header.text

'Main Page'

In [7]:
header_list=[]

for i in soup.find_all('h1'):
    header_list.append(i.text)
for i in soup.find_all('h2'):
    header_list.append(i.text)
for i in soup.find_all('h3'):
    header_list.append(i.text)
for i in soup.find_all('h4'):
    header_list.append(i.text)
for i in soup.find_all('h5'):
    header_list.append(i.text)
for i in soup.find_all('h6'):
    header_list.append(i.text)

In [8]:
header_list

['Main Page',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages',
 'Navigation menu',
 '\nPersonal tools\n',
 '\nNamespaces\n',
 '\nVariants\nexpanded\ncollapsed\n',
 '\nViews\n',
 '\nMore\nexpanded\ncollapsed\n',
 '\nSearch\n',
 '\nNavigation\n',
 '\nContribute\n',
 '\nTools\n',
 '\nPrint/export\n',
 '\nIn other projects\n',
 '\nLanguages\n']



# 2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [9]:
pg2=requests.get("https://www.imdb.com/chart/top/?ref_=nv_mv_250")

In [10]:
pg2

In [11]:
soup2=BeautifulSoup(pg2.content,'html.parser')

In [13]:
movie_tag=soup2.find('td',  class_='titleColumn')
movie_title=movie_tag.find('a')

In [14]:
movie_title=[]
movie_year=[]
movie_rating=[]
num=0
for i in soup2.find_all('td',  class_='titleColumn'):
    title=i.find('a')
    movie_title.append(title.text)
    year=i.find('span', class_='secondaryInfo')
    movie_year.append(year.text)
    num=num+1
    if num==100:
        break
num=0
for i in soup2.find_all('td', class_='ratingColumn imdbRating'):
    rating=i.find('strong')
    movie_rating.append(rating.text)
    num=num+1
    if num==100:
        break

In [15]:
print(len(movie_title),len(movie_year),len(movie_rating))

100 100 100

In [16]:
import pandas as pd

In [17]:
df=pd.DataFrame({'Movie Title':movie_title,'Rating':movie_rating,'Year of release':movie_year})
df

                              Movie Title Rating Year of release
0                The Shawshank Redemption    9.2          (1994)
1                           The Godfather    9.1          (1972)
2                  The Godfather: Part II    9.0          (1974)
3                         The Dark Knight    9.0          (2008)
4                            12 Angry Men    8.9          (1957)
..                                    ...    ...             ...
95                                 Jagten    8.3          (2012)
96                    Requiem for a Dream    8.3          (2000)
97                    Singin' in the Rain    8.3          (1952)
98                     North by Northwest    8.3          (1959)
99  Eternal Sunshine of the Spotless Mind    8.3          (2004)

[100 rows x 3 columns]



# 3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year ofrelease) and make data frame.

In [18]:
pg3=requests.get("https://www.imdb.com/india/top-rated-indian-movies/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=461131e5-5af0-4e50-bee2-223fad1e00ca&pf_rd_r=JC8DKTDE2R9YQTMZTA54&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=india.toprated&ref_=fea_india_ss_toprated_india_tr_india250_sm")

In [19]:
soup3=BeautifulSoup(pg3.content,'html.parser')

In [20]:
movie_title=[]
movie_year=[]
movie_rating=[]
num=0
for i in soup3.find_all('td',  class_='titleColumn'):
    title=i.find('a')
    movie_title.append(title.text)
    year=i.find('span', class_='secondaryInfo')
    movie_year.append(year.text)
    num=num+1
    if num==100:
        break
num=0
for i in soup3.find_all('td', class_='ratingColumn imdbRating'):
    rating=i.find('strong')
    movie_rating.append(rating.text)
    num=num+1
    if num==100:
        break

In [21]:
print(len(movie_title),len(movie_year),len(movie_rating))

100 100 100

In [22]:
df=pd.DataFrame({'Movie Title':movie_title,'Rating':movie_rating,'Year of release':movie_year})
df

            Movie Title Rating Year of release
0              Jai Bhim    8.5          (2021)
1     Pariyerum Perumal    8.5          (2018)
2               Nayakan    8.5          (1987)
3            Anbe Sivam    8.5          (2003)
4     C/o Kancharapalem    8.5          (2018)
..                  ...    ...             ...
95  Munna Bhai M.B.B.S.    8.1          (2003)
96            Sarfarosh    8.1          (1999)
97                 Roja    8.1          (1992)
98                Queen    8.1          (2013)
99       Dil Chahta Hai    8.1          (2001)

[100 rows x 3 columns]


# 4) Write a python program to scrape product name, price and discounts from https://meesho.com/bagsladies/pl/p7vbp .

In [23]:
pg4=requests.get("https://meesho.com/bags-ladies/pl/p7vbp")

In [24]:
pg4

In [25]:
soup4=BeautifulSoup(pg4.content,'html.parser')

In [26]:
link='Card__BaseCard-sc-b3n78k-0 dUNFgg NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS'
pname_tag=soup4.find('div', class_=link)
pname=pname_tag.find('p')
pprice=pname_tag.find('h5')

In [27]:
print(pname.text,pprice.text)

khatushyam collection  Women Handbag - Extra Spacious ₹374

In [28]:
link2='Card__BaseCard-sc-b3n78k-0 iJCKg NewProductCard__DiscountRow-sc-j0e7tu-15 kUcVjG NewProductCard__DiscountRow-sc-j0e7tu-15 kUcVjG'
pdiscount_tag=soup4.find('div',class_=link2)
pdiscount=pdiscount_tag.find('p')
pdiscount.text.split()[0]

'₹100'

In [29]:
pname=[]
pprice=[]
pdiscount=[]
for i in soup4.find_all('div', class_=link):
    name=i.find('p')
    pname.append(name.text)
    price=i.find('h5')
    pprice.append(price.text)
    
for i in soup4.find_all('div', class_=link2):
    discount=i.find('p')
    pdiscount.append(discount.text.split()[0])

In [30]:
df=pd.DataFrame({'Product Name':pname,'Product Price':pprice,'Product Discount':pdiscount})
df

,Product Name,Product Price,Product Discount
0,khatushyam collection Women Handbag - Extra S...,₹374,₹100
1,bandhani thela,₹228,₹97
2,Women's Handbag With Sling Bag & Wristlet (Set...,₹421,₹100
3,AZED Collections Women's PU Leather Handbag - ...,₹566,₹100
4,Handbag,₹365,₹100
5,Woman Ladies Girls Handmade bags for women zip...,₹384,₹100
6,YouRdreamZ jute lunch bag shopping bag for men...,₹165,₹70
7,Shoulder Handbag,₹384,₹100
8,Handbag,₹416,₹100
9,ELEGANT HANDBAG,₹231,₹98
10,Women's Nylon Fabric Casual Hand Bag (Sandal w...,₹435,₹100
11,STYLISH WOMEN PURSE,₹484,₹100
12,STYLISH WOMEN PURSE,₹484,₹100
13,STYLISH WOMEN PURSE,₹534,₹100
14,STYLISH WOMEN BAGS,₹515,₹100
15,Style big woman side bag,₹203,₹86
16,Handbag,₹365,₹100
17,QUALITY Handbags,₹416,₹100
18,Handbag,₹280,₹100
19,Women's Handbag with Sling Bag & Coin Pouch(Se...,₹468,₹100

# 5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
b) Top 10 ODI Batsmen along with the records of their team and rating.
c) Top 10 ODI bowlers along with the records of their team and rating.

In [31]:
pg5a=requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')

In [32]:
pg5a

In [33]:
soup5a=BeautifulSoup(pg5a.content,'html.parser')

In [34]:
cname=[]
matches=[]
points=[]
rating=[]

matches.append(soup5a.find('td', class_='rankings-block__banner--matches').text)
points.append(soup5a.find('td', class_='rankings-block__banner--points').text)
rating.append(soup5a.find('td', class_='rankings-block__banner--rating u-text-right').text.strip())

num=0
for i in soup5a.find_all('span',class_='u-hide-phablet'):
    cname.append(i.text)
    num=num+1
    if num==10:
        break
num=2
for i in soup5a.find_all('td', class_='table-body__cell u-center-text'):
    if(num%2==0):
        matches.append(i.text)
    else:
        points.append(i.text)
    num=num+1
    if num==20:
        break

num=1
for i in soup5a.find_all('td', class_='table-body__cell u-text-right rating'):
    rating.append(i.text)
    num=num+1
    if num==10:
        break

In [35]:
df=pd.DataFrame({'Country Name':cname,'Matches':matches,'Points':points,'Rating':rating})
df

   Country Name Matches Points Rating
0   New Zealand      17  2,054    121
1       England      32  3,793    119
2     Australia      28  3,244    116
3         India      32  3,624    113
4  South Africa      25  2,459     98
5      Pakistan      27  2,524     93
6    Bangladesh      30  2,740     91
7   West Indies      30  2,523     84
8     Sri Lanka      32  2,657     83
9   Afghanistan      17  1,054     62

In [36]:
pg5b=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')

In [37]:
soup5b=BeautifulSoup(pg5b.content,'html.parser')

In [38]:
bat_name=[]
bat_team=[]
bat_rating=[]
bow_name=[]
bow_team=[]
bow_rating=[]

num=0
for i in soup5b.find_all('div', class_='rankings-block__banner--name'):
    if num==0:
        bat_name.append(i.text)
    if num==1:
        bow_name.append(i.text)
    num=num+1
num=0
for i in soup5b.find_all('div', class_='rankings-block__banner--nationality'):
    if num==0:
        bat_team.append(i.text.split()[0])
    if num==1:
        bow_team.append(i.text.split()[0])
    num=num+1
num=0
for i in soup5b.find_all('div', class_='rankings-block__banner--rating'):
    if num==0:
        bat_rating.append(i.text)
    if num==1:
        bow_rating.append(i.text)
    num=num+1
    

num=1
for i in soup5b.find_all('td',class_='table-body__cell name'):   
    if num<10:
        bat_name.append(i.text.strip())
    else:
        bow_name.append(i.text.strip())
    num=num+1
    if num==19:
        break
num=1
for i in soup5b.find_all('span', class_='table-body__logo-text'):
    if num<10:
        bat_team.append(i.text)
    else:
        bow_team.append(i.text)
    num=num+1
    if num==19:
        break

num=1
for i in soup5b.find_all('td', class_='table-body__cell u-text-right rating'):
    if num<10:
        bat_rating.append(i.text)
    else:
        bow_rating.append(i.text)
    num=num+1
    if num==19:
        break

In [39]:
df=pd.DataFrame({'Player Name':bat_name,'Team':bat_team,'Rating':bat_rating})
df

       Player Name Team Rating
0       Babar Azam  PAK    873
1      Virat Kohli  IND    844
2     Rohit Sharma  IND    813
3      Ross Taylor   NZ    801
4      Aaron Finch  AUS    779
5   Jonny Bairstow  ENG    775
6     David Warner  AUS    762
7        Shai Hope   WI    758
8  Kane Williamson   NZ    754
9  Quinton de Kock   SA    743

In [40]:
df=pd.DataFrame({'Player Name':bow_name,'Team':bow_team,'Rating':bow_rating})
df

        Player Name Team Rating
0       Trent Boult   NZ    737
1    Josh Hazlewood  AUS    709
2  Mujeeb Ur Rahman  AFG    708
3      Chris Woakes  ENG    700
4      Mehedi Hasan  BAN    692
5        Matt Henry   NZ    691
6    Jasprit Bumrah  IND    679
7    Mitchell Starc  AUS    652
8   Shakib Al Hasan  BAN    650
9     Kagiso Rabada   SA    643

# 6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
b) Top 10 women’s ODI Batting players along with the records of their team and rating.
c) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [41]:
pg6a=requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')

In [42]:
soup6a=BeautifulSoup(pg6a.content,'html.parser')

In [43]:
cname=[]
matches=[]
points=[]
rating=[]

matches.append(soup6a.find('td', class_='rankings-block__banner--matches').text)
points.append(soup6a.find('td', class_='rankings-block__banner--points').text)
rating.append(soup6a.find('td', class_='rankings-block__banner--rating u-text-right').text.strip())

num=0
for i in soup6a.find_all('span',class_='u-hide-phablet'):
    cname.append(i.text)
    num=num+1
    if num==10:
        break
num=2
for i in soup6a.find_all('td', class_='table-body__cell u-center-text'):
    if(num%2==0):
        matches.append(i.text)
    else:
        points.append(i.text)
    num=num+1
    if num==20:
        break

num=1
for i in soup6a.find_all('td', class_='table-body__cell u-text-right rating'):
    rating.append(i.text)
    num=num+1
    if num==10:
        break

In [44]:
df=pd.DataFrame({'Country Name':cname,'Matches':matches,'Points':points,'Rating':rating})
df

   Country Name Matches Points Rating
0     Australia      17  2,746    162
1  South Africa      19  2,307    121
2       England      18  2,148    119
3         India      17  1,899    112
4    Bangladesh       5    475     95
5   New Zealand      19  1,668     88
6   West Indies      19  1,658     87
7      Pakistan      18  1,226     68
8       Ireland       5    240     48
9     Sri Lanka       5    233     47

In [45]:
pg6b=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi')

In [46]:
soup6b=BeautifulSoup(pg6b.content,'html.parser')

In [47]:
bat_name=[]
bat_team=[]
bat_rating=[]
bow_name=[]
bow_team=[]
bow_rating=[]

num=0
for i in soup6b.find_all('div', class_='rankings-block__banner--name'):
    if num==0:
        bat_name.append(i.text)
    if num==2:
        bow_name.append(i.text)
    num=num+1
num=0
for i in soup6b.find_all('div', class_='rankings-block__banner--nationality'):
    if num==0:
        bat_team.append(i.text.split()[0])
    if num==2:
        bow_team.append(i.text.split()[0])
    num=num+1
num=0
for i in soup6b.find_all('div', class_='rankings-block__banner--rating'):
    if num==0:
        bat_rating.append(i.text)
    if num==2:
        bow_rating.append(i.text)
    num=num+1
    

num=1
for i in soup6b.find_all('td',class_='table-body__cell name'):   
    if num<10:
        bat_name.append(i.text.strip())
    if num>18:
        bow_name.append(i.text.strip())
    num=num+1
    if num==28:
        break
num=1
for i in soup6b.find_all('span', class_='table-body__logo-text'):
    if num<10:
        bat_team.append(i.text)
    if num>18:
        bow_team.append(i.text)
    num=num+1
    if num==28:
        break

num=1
for i in soup6b.find_all('td', class_='table-body__cell u-text-right rating'):
    if num<10:
        bat_rating.append(i.text)
    if num>18:
        bow_rating.append(i.text)
    num=num+1
    if num==28:
        break

In [48]:
df=pd.DataFrame({'Player Name':bat_name,'Team':bat_team,'Rating':bat_rating})
df

         Player Name Team Rating
0        Lizelle Lee   SA    761
1       Alyssa Healy  AUS    750
2        Mithali Raj  IND    738
3     Tammy Beaumont  ENG    728
4  Amy Satterthwaite   NZ    717
5    Smriti Mandhana  IND    710
6        Meg Lanning  AUS    699
7        Beth Mooney  AUS    690
8    Stafanie Taylor   WI    676
9     Heather Knight  ENG    674

In [49]:
df=pd.DataFrame({'Player Name':bow_name,'Team':bow_team,'Rating':bow_rating})
df

        Player Name Team Rating
0    Marizanne Kapp   SA    384
1    Natalie Sciver  ENG    372
2      Ellyse Perry  AUS    365
3   Stafanie Taylor   WI    319
4     Deepti Sharma  IND    299
5  Ashleigh Gardner  AUS    275
6  Dane van Niekerk   SA    274
7   Hayley Matthews   WI    272
8     Jess Jonassen  AUS    272
9   Katherine Brunt  ENG    272

# 7) Write a python program to scrape details of all the posts from coreyms.com. Scrape the heading, date, content and the code for the video from the link for the youtube video from the post.

In [50]:
pg7=requests.get('https://coreyms.com')

In [51]:
pg7

In [52]:
soup7=BeautifulSoup(pg7.content,'html.parser')

In [53]:
heading=[]
date=[]
content=[]
video=[]

for i in soup7.find_all('a',class_='entry-title-link'):
    heading.append(i.text)
for i in soup7.find_all('time',class_='entry-time'):
    date.append(i.text)
for i in soup7.find_all('div',class_='entry-content'):
    cont=i.find('p')
    content.append(cont.text)
    try:
        vid=i.find('span',class_='embed-youtube')
        link=vid.find('iframe',class_='youtube-player')
        video.append(link['src'].split("?")[0].split("/")[-1])
    except:
        video.append('NA')

In [54]:
len(heading),len(date),len(content),len(video)

(10, 10, 10, 10)

In [55]:
df=pd.DataFrame({'Heading':heading,'Date':date,'Content':content,'Video link':video})
df

,Heading,Date,Content,Video link
0,Python Tutorial: Zip Files – Creating and Extr...,"November 19, 2019","In this video, we will be learning how to crea...",z0gguhEmWiY
1,Python Data Science Tutorial: Analyzing the 20...,"October 17, 2019","In this Python Programming video, we will be l...",_P7X8tMplsw
2,Python Multiprocessing Tutorial: Run Code in P...,"September 21, 2019","In this Python Programming video, we will be l...",fKl2JW_qrso
3,Python Threading Tutorial: Run Code Concurrent...,"September 12, 2019","In this Python Programming video, we will be l...",IEEhzQoKtQU
4,Update (2019-09-03),"September 3, 2019",Hey everyone. I wanted to give you an update o...,NA
5,Python Quick Tip: The Difference Between “==” ...,"August 6, 2019","In this Python Programming Tutorial, we will b...",mO_dS3rXDIs
6,Python Tutorial: Calling External Commands Usi...,"July 24, 2019","In this Python Programming Tutorial, we will b...",2Fp1N6dof0Y
7,Visual Studio Code (Windows) – Setting up a Py...,"May 1, 2019","In this Python Programming Tutorial, we will b...",-nh9rCzPJ20
8,Visual Studio Code (Mac) – Setting up a Python...,"May 1, 2019","In this Python Programming Tutorial, we will b...",06I63_p-2A4
9,Clarifying the Issues with Mutable Default Arg...,"April 24, 2019","In this Python Programming Tutorial, we will b...",_JGmemuINww

# 8) Write a python program to scrape house details from mentioned URL. It should include house title, location, area, EMI and price from https://www.nobroker.in/ .Enter three localities which are Indira Nagar, Jayanagar, Rajaji Nagar.

In [56]:
pg8=requests.get('https://www.nobroker.in/property/sale/bangalore/multiple?searchParam=W3sibGF0IjoxMi45NzgzNjkyLCJsb24iOjc3LjY0MDgzNTYsInBsYWNlSWQiOiJDaElKa1FOM0dLUVdyanNSTmhCUUpyaEdEN1UiLCJwbGFjZU5hbWUiOiJJbmRpcmFuYWdhciJ9LHsibGF0IjoxMi45MzA3NzM1LCJsb24iOjc3LjU4MzgzMDIsInBsYWNlSWQiOiJDaElKMmRkbFo1Z1ZyanNSaDFCT0FhZi1vcnMiLCJwbGFjZU5hbWUiOiJKYXlhbmFnYXIifSx7ImxhdCI6MTIuOTk4MTczMiwibG9uIjo3Ny41NTMwNDQ1OTk5OTk5OSwicGxhY2VJZCI6IkNoSUp4Zlc0RFBNOXJqc1JLc05URy01cF9RUSIsInBsYWNlTmFtZSI6IlJhamFqaW5hZ2FyIn1d&radius=2.0&city=bangalore&locality=Indiranagar,&locality=Jayanagar,&locality=Rajajinagar')

In [57]:
pg8

In [58]:
soup8=BeautifulSoup(pg8.content,'html.parser')

In [63]:
title=[]
location=[]
area=[]
emi=[]
price=[]
for i in soup8.find_all('h2',class_="heading-6 font-semi-bold nb__25Cl7"):
    title.append(i.text.split(",")[0])
    location.append(i.text.split("In ")[-1].split(",")[-1])
    

num=3  
for i in soup8.find_all('div',class_='font-semi-bold heading-6'):
    if num%3==0:
        area.append(i.text)
    elif num%3==1:
        emi.append(i.text)
    else:
        price.append(i.text)
    num=num+1

In [64]:
df=pd.DataFrame({'Title':title,'Location':location,'Area':area,'Estimated EMI':emi,'Price':price})
df

,Title,Location,Area,Estimated EMI,Price
0,3 BHK Flat For Sale In Shanti Park Apartment...,Jayanagar,"1,420 sqft","₹71,643/Month",₹1.25 Crores
1,4+ BHK In Independent House For Sale In Raja...,Rajajinaga,"2,240 sqft","₹83,679/Month",₹1.46 Crores
2,3 BHK Flat For Sale In Mantri Gardens Apartm...,Jayanagar,"1,485 sqft","₹85,971/Month",₹1.5 Crores
3,2 BHK Flat For Sale In Sri Sai Durga Residen...,Indira Nagar,"1,500 sqft","₹60,180/Month",₹1.05 Crores
4,2 BHK Apartment For Sale In Team Heritage Ap...,Indiranagar,"1,100 sqft","₹57,314/Month",₹1 Crore
5,3 BHK Flat For Sale In Total Environment Lif...,Jayanagar,"2,628 sqft",₹1.72 Lacs/Month,₹3 Crores
6,2 BHK Flat For Sale In Maple Apartments In I...,Indiranagar,925 sqft,"₹37,254/Month",₹65 Lacs
7,4+ BHK In Independent House For Sale In Jaya...,Jayanagar,"2,195 sqft",₹2.96 Lacs/Month,₹5.16 Crores
8,3 BHK Flat For Sale In Beverly Apartments In...,Indiranagar,"1,780 sqft","₹91,703/Month",₹1.6 Crores
9,4 BHK Flat For Sale In Rrbc Piccassso In Jay...,Jayanagar,"4,859 sqft",₹3.91 Lacs/Month,₹6.83 Crores
10,3 BHK Flat For Sale In Rrbc Piccassso In Jay...,Jayanagar,"2,037 sqft",₹1.69 Lacs/Month,₹2.94 Crores
11,3 BHK Apartment For Sale In Adarsh Court Apa...,Jayanagar,"1,990 sqft",₹2.01 Lacs/Month,₹3.5 Crores
12,4+ BHK In Independent House For Sale In Raja...,Rajaji Nagar,"1,350 sqft",₹1.96 Lacs/Month,₹3.42 Crores
13,1 BHK Flat For Sale In Rajajinagar In Rajaji...,Rajaji Nagar,650 sqft,"₹28,657/Month",₹50 Lacs
14,3 BHK Flat For Sale In Vaishali Residency In...,Indiranagar,"1,300 sqft","₹65,911/Month",₹1.15 Crores
15,2 BHK Apartment For Sale In Benaka Towers In...,Indiranagar,"1,378 sqft","₹56,168/Month",₹98 Lacs
16,3 BHK Flat For Sale In Livintique Residence ...,Indiranagar,"2,450 sqft",₹2.01 Lacs/Month,₹3.5 Crores
17,4 BHK Flat For Sale In Phoenix One Bangalor...,Rajajinagar,"2,901 sqft",₹2.72 Lacs/Month,₹4.75 Crores
18,4+ BHK In Independent House For Sale In Bana...,Banashankari,"3,600 sqft",₹3.15 Lacs/Month,₹5.5 Crores
19,4+ BHK Flat For Sale In Tilak Nagar,Jayanagar,"2,000 sqft","₹45,278/Month",₹79 Lacs
20,3 BHK Flat For Sale In Santaclara In 18th M...,18th Main Jayanagara,"1,400 sqft","₹80,240/Month",₹1.4 Crores
21,4+ BHK Flat For Sale In Linea Apoorva,18th Main Road,"5,100 sqft",₹4.3 Lacs/Month,₹7.5 Crores
22,3 BHK Flat For Sale In Brigade Gateway In Ra...,Rajaji Nagar,"1,640 sqft",₹1.83 Lacs/Month,₹3.2 Crores
23,3 BHK In Independent House For Sale In Rajaj...,Rajaji Nagar,"1,200 sqft","₹40,120/Month",₹70 Lacs
24,3 BHK Apartment For Sale In Brigade Gateway ...,Rajaji Nagar,"1,640 sqft",₹2.01 Lacs/Month,₹3.5 Crores

# 9) Write a python program to scrape mentioned details from dineout.co.in :
i) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image URL

In [65]:
pg9=requests.get('https://www.dineout.co.in/mumbai-restaurants?search_str=mumbai')

In [66]:
pg9

In [67]:
soup9=BeautifulSoup(pg9.content)

In [68]:
rname=[]
cuisine=[]
location=[]
rating=[]
image_url=[]

for i in soup9.find_all('a',class_='restnt-name ellipsis'):
    rname.append(i.text)
for i in soup9.find_all('span',class_='double-line-ellipsis'):
    cuisine.append(i.text.split("|")[1])
for i in soup9.find_all('div',class_='restnt-loc ellipsis'):
    location.append(i.text)
for i in soup9.find_all('div',class_='img-wrap'):
    rating.append(i.text.strip()[-3:])
for i in soup9.find_all('img',class_='no-img'):
    image_url.append(i['data-src'])

In [69]:
df=pd.DataFrame({'Restaurant Name':rname,'Cuisine':cuisine,'Location':location,'Rating':rating,'Image url':image_url})
df

,Restaurant Name,Cuisine,Location,Rating,Image url
0,Pop Tate's,"Chinese, Continental, Italian, Seafood, Sizzlers","R City Mall,Ghatkopar West, Central Suburbs",4.3,https://im1.dineout.co.in/images/uploads/resta...
1,Pop Tate's,"Chinese, Continental, Italian, Seafood, Sizzlers","Mayfair Sonata Green CHS,Vikhroli West, Centra...",4.3,https://im1.dineout.co.in/images/uploads/resta...
2,Episode One,"Continental, Asian, Modern Indian","Powai, Powai",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,ABs - Absolute Barbecues,"Barbecue, Chinese, North Indian","Chandivali, Powai",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,Sigree Global Grill,"North Indian, Biryani, Italian","Ventura Building,Powai, Powai",4.4,https://im1.dineout.co.in/images/uploads/resta...
5,Hitchki,"Modern Indian, North Indian, Fast Food","Hiranandani Business Park,Powai, Powai",4.5,https://im1.dineout.co.in/images/uploads/resta...
6,Lord of the Drinks,"Multi-Cuisine, Chinese, Continental, Italian,...","Powai, Powai",4.2,https://im1.dineout.co.in/images/uploads/resta...
7,Powai Social,"Multi-Cuisine, Asian, Chinese, Continental, F...","Delphi Building,Powai, Powai",4.2,https://im1.dineout.co.in/images/uploads/resta...
8,PizzaExpress,"European, Fast Food, Italian","Ventura Building,Powai, Powai",4.4,https://im1.dineout.co.in/images/uploads/resta...
9,Timbuctoo,"Italian, Continental, North Indian","Mayfair Sonata Green CHS,Vikhroli West, Centra...",4.3,https://im1.dineout.co.in/images/uploads/resta...
10,Kake Da Hotel,"Chinese, Mughlai, North Indian","Powai, Powai",4.5,https://im1.dineout.co.in/images/uploads/resta...
11,Chili’s American Grill and Bar,"American, Mexican, Tex Mex","Ventura Building,Powai, Powai",4.2,https://im1.dineout.co.in/images/uploads/resta...
12,Foo,"Asian, Chinese, Japanese, Sushi","Vikhroli West, Central Suburbs",4.5,https://im1.dineout.co.in/images/uploads/resta...
13,Global Fusion,"Chinese, North Indian, Sushi","Times Square,Near Andheri East Station, Andher...",4.5,https://im1.dineout.co.in/images/uploads/resta...
14,The Sassy Spoon,"Desserts, Continental, European, Italian","Delphi Building,Powai, Powai",4.4,https://im1.dineout.co.in/images/uploads/resta...
15,Sbarro - New York Pizza,"Pizza, Fast Food","Kailash Business Park,Vikhroli West, Central S...",5,https://im1.dineout.co.in/images/uploads/resta...
16,House of Mandarin,"Asian, Chinese, Seafood, Sushi","Delphi Building,Powai, Powai",4.5,https://im1.dineout.co.in/images/uploads/resta...
17,Pop Tate's,"Chinese, Continental, Italian, Seafood, Sizzlers","Phoenix Marketcity Mall,Kurla West, Central Su...",4.3,https://im1.dineout.co.in/images/uploads/resta...
18,Finch Brew Cafe,"Continental, Fast Food","City Park Building,Powai, Powai",4.1,https://im1.dineout.co.in/images/uploads/resta...
19,Taco Bell,"Fast Food, American, Mexican","R City Mall,Ghatkopar West, Central Suburbs",4,https://im1.dineout.co.in/images/uploads/resta...
20,Vikhroli Social,"Continental, Finger Food, North Indian, Ameri...","Imagine Studio,Vikhroli East, Central Suburbs",4.4,https://im1.dineout.co.in/images/uploads/resta...

# 10) Write a python program to scrape first 10 product details which include product name , price , Image URL from
https://www.bewakoof.com/women-tshirts?ga_q=tshirts .

In [70]:
pg10=requests.get("https://www.bewakoof.com/women-tshirts?ga_q=tshirts")

In [71]:
pg10

In [72]:
soup10=BeautifulSoup(pg10.content)

In [73]:
pname=[]
price=[]
img_url=[]

for i in soup10.find_all('div',class_='productCardDetail'):
    n=i.find('div')
    name=n.find('h3')
    pname.append(name.text)
    
for i in soup10.find_all('span',class_='discountedPriceText'):
    price.append(i.text)
    
for i in soup10.find_all('img',class_='productImgTag'):
    img_url.append(i['src'])

In [74]:
#trying to store all list in one for loop
pname=[]
price=[]
img_url=[]

for i in soup10.find_all('div',class_='productCardBox'):
    pdeatils=i.find('div',class_='productCardDetail')
    n=pdeatils.find('div')
    name=n.find('h3')
    pname.append(name.text)
    p=pdeatils.find('div',class_='productPriceBox clearfix')
    pr=p.find('span',class_='discountedPriceText')
    price.append(pr.text)
    im=i.find('div',class_='productCardImg false')
    ima=im.find('div')
    imag=ima.find('img',class_='productImgTag')
    img_url.append(imag['src'])

In [75]:
df=pd.DataFrame({'Product Name':pname,'Price':price,'Image url':img_url})
df

,Product Name,Price,Image url
0,Bounty Hunter Boyfriend T-Shirt,₹ 249,https://images.bewakoof.com/t320/bounty-hunter...
1,Diagonal Friends Half Sleeves T-Shirt (FRL),₹ 249,https://images.bewakoof.com/t320/diagonal-frie...
2,Classic Tj Logo Half Sleeve T-Shirt (TJL) Black,₹ 249,https://images.bewakoof.com/t320/classic-tj-lo...
3,Yoga se Hoga Women's Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/yoga-se-hoga-...
4,Climbing pocket panda Printed Red T-shirt,₹ 249,https://images.bewakoof.com/t320/climbing-pock...
5,Minimal Believe Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/minimal-belie...
6,Bunny Rabbit Pocket Printed Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/bunny-rabbit-...
7,Friends logo (FRL) Printed Half Sleeve T-shirt,₹ 249,https://images.bewakoof.com/t320/friends-logo-...
8,Princess Squad Half Sleeve Printed T-Shirt,₹ 249,https://images.bewakoof.com/t320/princess-squa...
9,Olive Night Half Sleeve T-Shirt,₹ 299,https://images.bewakoof.com/t320/olive-night-h...

In [76]:
df=pd.DataFrame({'Product Name':pname,'Price':price,'Image url':img_url})
df

,Product Name,Price,Image url
0,Bounty Hunter Boyfriend T-Shirt,₹ 249,https://images.bewakoof.com/t320/bounty-hunter...
1,Diagonal Friends Half Sleeves T-Shirt (FRL),₹ 249,https://images.bewakoof.com/t320/diagonal-frie...
2,Classic Tj Logo Half Sleeve T-Shirt (TJL) Black,₹ 249,https://images.bewakoof.com/t320/classic-tj-lo...
3,Yoga se Hoga Women's Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/yoga-se-hoga-...
4,Climbing pocket panda Printed Red T-shirt,₹ 249,https://images.bewakoof.com/t320/climbing-pock...
5,Minimal Believe Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/minimal-belie...
6,Bunny Rabbit Pocket Printed Half Sleeve T-Shirt,₹ 249,https://images.bewakoof.com/t320/bunny-rabbit-...
7,Friends logo (FRL) Printed Half Sleeve T-shirt,₹ 249,https://images.bewakoof.com/t320/friends-logo-...
8,Princess Squad Half Sleeve Printed T-Shirt,₹ 249,https://images.bewakoof.com/t320/princess-squa...
9,Olive Night Half Sleeve T-Shirt,₹ 299,https://images.bewakoof.com/t320/olive-night-h...